// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.26.1
// source: sui/rpc/v2beta2/balance_change.proto

package v2beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The delta, or change, in balance for an address for a particular `Coin` type.
type BalanceChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The account address that is affected by this balance change event.
	Address *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// The `Coin` type of this balance change event.
	CoinType *string `protobuf:"bytes,2,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// The amount or change in balance.
	Amount        *string `protobuf:"bytes,3,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceChange) Reset() {
	*x = BalanceChange{}
	mi := &file_sui_rpc_v2beta2_balance_change_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChange) ProtoMessage() {}

func (x *BalanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_balance_change_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChange.ProtoReflect.Descriptor instead.
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_balance_change_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceChange) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *BalanceChange) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *BalanceChange) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

var File_sui_rpc_v2beta2_balance_change_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta2_balance_change_proto_rawDesc = "" +
	"\n" +
	"$sui/rpc/v2beta2/balance_change.proto\x12\x0fsui.rpc.v2beta2\"\x92\x01\n" +
	"\rBalanceChange\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01\x12 \n" +
	"\tcoin_type\x18\x02 \x01(\tH\x01R\bcoinType\x88\x01\x01\x12\x1b\n" +
	"\x06amount\x18\x03 \x01(\tH\x02R\x06amount\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\f\n" +
	"\n" +
	"_coin_typeB\t\n" +
	"\a_amountb\x06proto3"

var (
	file_sui_rpc_v2beta2_balance_change_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta2_balance_change_proto_rawDescData []byte
)

func file_sui_rpc_v2beta2_balance_change_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta2_balance_change_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta2_balance_change_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_balance_change_proto_rawDesc), len(file_sui_rpc_v2beta2_balance_change_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta2_balance_change_proto_rawDescData
}

var file_sui_rpc_v2beta2_balance_change_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2beta2_balance_change_proto_goTypes = []any{
	(*BalanceChange)(nil), // 0: sui.rpc.v2beta2.BalanceChange
}
var file_sui_rpc_v2beta2_balance_change_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta2_balance_change_proto_init() }
func file_sui_rpc_v2beta2_balance_change_proto_init() {
	if File_sui_rpc_v2beta2_balance_change_proto != nil {
		return
	}
	file_sui_rpc_v2beta2_balance_change_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_balance_change_proto_rawDesc), len(file_sui_rpc_v2beta2_balance_change_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2beta2_balance_change_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta2_balance_change_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2beta2_balance_change_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta2_balance_change_proto = out.File
	file_sui_rpc_v2beta2_balance_change_proto_goTypes = nil
	file_sui_rpc_v2beta2_balance_change_proto_depIdxs = nil
}
