// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.26.1
// source: sui/rpc/v2beta2/checkpoint.proto

package v2beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Checkpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The height of this checkpoint.
	SequenceNumber *uint64 `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3,oneof" json:"sequence_number,omitempty"`
	// The digest of this Checkpoint's CheckpointSummary.
	Digest *string `protobuf:"bytes,2,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// The `CheckpointSummary` for this checkpoint.
	Summary *CheckpointSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof" json:"summary,omitempty"`
	// An aggregated quorum signature from the validator committee that
	// certified this checkpoint.
	Signature *ValidatorAggregatedSignature `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	// The `CheckpointContents` for this checkpoint.
	Contents *CheckpointContents `protobuf:"bytes,5,opt,name=contents,proto3,oneof" json:"contents,omitempty"`
	// List of transactions included in this checkpoint.
	Transactions  []*ExecutedTransaction `protobuf:"bytes,6,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_sui_rpc_v2beta2_checkpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_checkpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_checkpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Checkpoint) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *Checkpoint) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *Checkpoint) GetSummary() *CheckpointSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Checkpoint) GetSignature() *ValidatorAggregatedSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Checkpoint) GetContents() *CheckpointContents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Checkpoint) GetTransactions() []*ExecutedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_sui_rpc_v2beta2_checkpoint_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta2_checkpoint_proto_rawDesc = "" +
	"\n" +
	" sui/rpc/v2beta2/checkpoint.proto\x12\x0fsui.rpc.v2beta2\x1a)sui/rpc/v2beta2/checkpoint_contents.proto\x1a(sui/rpc/v2beta2/checkpoint_summary.proto\x1a*sui/rpc/v2beta2/executed_transaction.proto\x1a\x1fsui/rpc/v2beta2/signature.proto\"\xc2\x03\n" +
	"\n" +
	"Checkpoint\x12,\n" +
	"\x0fsequence_number\x18\x01 \x01(\x04H\x00R\x0esequenceNumber\x88\x01\x01\x12\x1b\n" +
	"\x06digest\x18\x02 \x01(\tH\x01R\x06digest\x88\x01\x01\x12A\n" +
	"\asummary\x18\x03 \x01(\v2\".sui.rpc.v2beta2.CheckpointSummaryH\x02R\asummary\x88\x01\x01\x12P\n" +
	"\tsignature\x18\x04 \x01(\v2-.sui.rpc.v2beta2.ValidatorAggregatedSignatureH\x03R\tsignature\x88\x01\x01\x12D\n" +
	"\bcontents\x18\x05 \x01(\v2#.sui.rpc.v2beta2.CheckpointContentsH\x04R\bcontents\x88\x01\x01\x12H\n" +
	"\ftransactions\x18\x06 \x03(\v2$.sui.rpc.v2beta2.ExecutedTransactionR\ftransactionsB\x12\n" +
	"\x10_sequence_numberB\t\n" +
	"\a_digestB\n" +
	"\n" +
	"\b_summaryB\f\n" +
	"\n" +
	"_signatureB\v\n" +
	"\t_contentsb\x06proto3"

var (
	file_sui_rpc_v2beta2_checkpoint_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta2_checkpoint_proto_rawDescData []byte
)

func file_sui_rpc_v2beta2_checkpoint_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta2_checkpoint_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta2_checkpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_checkpoint_proto_rawDesc), len(file_sui_rpc_v2beta2_checkpoint_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta2_checkpoint_proto_rawDescData
}

var file_sui_rpc_v2beta2_checkpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2beta2_checkpoint_proto_goTypes = []any{
	(*Checkpoint)(nil),                   // 0: sui.rpc.v2beta2.Checkpoint
	(*CheckpointSummary)(nil),            // 1: sui.rpc.v2beta2.CheckpointSummary
	(*ValidatorAggregatedSignature)(nil), // 2: sui.rpc.v2beta2.ValidatorAggregatedSignature
	(*CheckpointContents)(nil),           // 3: sui.rpc.v2beta2.CheckpointContents
	(*ExecutedTransaction)(nil),          // 4: sui.rpc.v2beta2.ExecutedTransaction
}
var file_sui_rpc_v2beta2_checkpoint_proto_depIdxs = []int32{
	1, // 0: sui.rpc.v2beta2.Checkpoint.summary:type_name -> sui.rpc.v2beta2.CheckpointSummary
	2, // 1: sui.rpc.v2beta2.Checkpoint.signature:type_name -> sui.rpc.v2beta2.ValidatorAggregatedSignature
	3, // 2: sui.rpc.v2beta2.Checkpoint.contents:type_name -> sui.rpc.v2beta2.CheckpointContents
	4, // 3: sui.rpc.v2beta2.Checkpoint.transactions:type_name -> sui.rpc.v2beta2.ExecutedTransaction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta2_checkpoint_proto_init() }
func file_sui_rpc_v2beta2_checkpoint_proto_init() {
	if File_sui_rpc_v2beta2_checkpoint_proto != nil {
		return
	}
	file_sui_rpc_v2beta2_checkpoint_contents_proto_init()
	file_sui_rpc_v2beta2_checkpoint_summary_proto_init()
	file_sui_rpc_v2beta2_executed_transaction_proto_init()
	file_sui_rpc_v2beta2_signature_proto_init()
	file_sui_rpc_v2beta2_checkpoint_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_checkpoint_proto_rawDesc), len(file_sui_rpc_v2beta2_checkpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2beta2_checkpoint_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta2_checkpoint_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2beta2_checkpoint_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta2_checkpoint_proto = out.File
	file_sui_rpc_v2beta2_checkpoint_proto_goTypes = nil
	file_sui_rpc_v2beta2_checkpoint_proto_depIdxs = nil
}
