// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.26.1
// source: sui/rpc/v2beta2/error_reason.proto

package v2beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ERROR_REASON_UNKNOWN ErrorReason = 0
	ErrorReason_FIELD_INVALID        ErrorReason = 1
	ErrorReason_FIELD_MISSING        ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "ERROR_REASON_UNKNOWN",
		1: "FIELD_INVALID",
		2: "FIELD_MISSING",
	}
	ErrorReason_value = map[string]int32{
		"ERROR_REASON_UNKNOWN": 0,
		"FIELD_INVALID":        1,
		"FIELD_MISSING":        2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2beta2_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2beta2_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_sui_rpc_v2beta2_error_reason_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta2_error_reason_proto_rawDesc = "" +
	"\n" +
	"\"sui/rpc/v2beta2/error_reason.proto\x12\x0fsui.rpc.v2beta2*M\n" +
	"\vErrorReason\x12\x18\n" +
	"\x14ERROR_REASON_UNKNOWN\x10\x00\x12\x11\n" +
	"\rFIELD_INVALID\x10\x01\x12\x11\n" +
	"\rFIELD_MISSING\x10\x02b\x06proto3"

var (
	file_sui_rpc_v2beta2_error_reason_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta2_error_reason_proto_rawDescData []byte
)

func file_sui_rpc_v2beta2_error_reason_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta2_error_reason_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta2_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_error_reason_proto_rawDesc), len(file_sui_rpc_v2beta2_error_reason_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta2_error_reason_proto_rawDescData
}

var file_sui_rpc_v2beta2_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sui_rpc_v2beta2_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: sui.rpc.v2beta2.ErrorReason
}
var file_sui_rpc_v2beta2_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta2_error_reason_proto_init() }
func file_sui_rpc_v2beta2_error_reason_proto_init() {
	if File_sui_rpc_v2beta2_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_error_reason_proto_rawDesc), len(file_sui_rpc_v2beta2_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2beta2_error_reason_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta2_error_reason_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2beta2_error_reason_proto_enumTypes,
	}.Build()
	File_sui_rpc_v2beta2_error_reason_proto = out.File
	file_sui_rpc_v2beta2_error_reason_proto_goTypes = nil
	file_sui_rpc_v2beta2_error_reason_proto_depIdxs = nil
}
