// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.26.1
// source: sui/rpc/v2beta2/executed_transaction.proto

package v2beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutedTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digest of this Transaction.
	Digest *string `protobuf:"bytes,1,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// The transaction itself.
	Transaction *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// List of user signatures that are used to authorize the
	// execution of this transaction.
	Signatures []*UserSignature `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// The `TransactionEffects` for this transaction.
	Effects *TransactionEffects `protobuf:"bytes,4,opt,name=effects,proto3,oneof" json:"effects,omitempty"`
	// The `TransactionEvents` for this transaction.
	//
	// This field might be empty, even if it was explicitly requested, if the
	// transaction didn't produce any events.
	// `sui.types.TransactionEffects.events_digest` is populated if the
	// transaction produced any events.
	Events *TransactionEvents `protobuf:"bytes,5,opt,name=events,proto3,oneof" json:"events,omitempty"`
	// The sequence number for the checkpoint that includes this transaction.
	Checkpoint *uint64 `protobuf:"varint,6,opt,name=checkpoint,proto3,oneof" json:"checkpoint,omitempty"`
	// The Unix timestamp of the checkpoint that includes this transaction.
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	BalanceChanges []*BalanceChange       `protobuf:"bytes,8,rep,name=balance_changes,json=balanceChanges,proto3" json:"balance_changes,omitempty"`
	// Set of input objects used during the execution of this transaction.
	InputObjects []*Object `protobuf:"bytes,10,rep,name=input_objects,json=inputObjects,proto3" json:"input_objects,omitempty"`
	// Set of output objects produced from the execution of this transaction.
	OutputObjects []*Object `protobuf:"bytes,11,rep,name=output_objects,json=outputObjects,proto3" json:"output_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutedTransaction) Reset() {
	*x = ExecutedTransaction{}
	mi := &file_sui_rpc_v2beta2_executed_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutedTransaction) ProtoMessage() {}

func (x *ExecutedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_executed_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutedTransaction.ProtoReflect.Descriptor instead.
func (*ExecutedTransaction) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_executed_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutedTransaction) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *ExecutedTransaction) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ExecutedTransaction) GetSignatures() []*UserSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *ExecutedTransaction) GetEffects() *TransactionEffects {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *ExecutedTransaction) GetEvents() *TransactionEvents {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ExecutedTransaction) GetCheckpoint() uint64 {
	if x != nil && x.Checkpoint != nil {
		return *x.Checkpoint
	}
	return 0
}

func (x *ExecutedTransaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutedTransaction) GetBalanceChanges() []*BalanceChange {
	if x != nil {
		return x.BalanceChanges
	}
	return nil
}

func (x *ExecutedTransaction) GetInputObjects() []*Object {
	if x != nil {
		return x.InputObjects
	}
	return nil
}

func (x *ExecutedTransaction) GetOutputObjects() []*Object {
	if x != nil {
		return x.OutputObjects
	}
	return nil
}

var File_sui_rpc_v2beta2_executed_transaction_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta2_executed_transaction_proto_rawDesc = "" +
	"\n" +
	"*sui/rpc/v2beta2/executed_transaction.proto\x12\x0fsui.rpc.v2beta2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$sui/rpc/v2beta2/balance_change.proto\x1a\x1dsui/rpc/v2beta2/effects.proto\x1a\x1bsui/rpc/v2beta2/event.proto\x1a\x1csui/rpc/v2beta2/object.proto\x1a\x1fsui/rpc/v2beta2/signature.proto\x1a!sui/rpc/v2beta2/transaction.proto\"\xb6\x05\n" +
	"\x13ExecutedTransaction\x12\x1b\n" +
	"\x06digest\x18\x01 \x01(\tH\x00R\x06digest\x88\x01\x01\x12C\n" +
	"\vtransaction\x18\x02 \x01(\v2\x1c.sui.rpc.v2beta2.TransactionH\x01R\vtransaction\x88\x01\x01\x12>\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x1e.sui.rpc.v2beta2.UserSignatureR\n" +
	"signatures\x12B\n" +
	"\aeffects\x18\x04 \x01(\v2#.sui.rpc.v2beta2.TransactionEffectsH\x02R\aeffects\x88\x01\x01\x12?\n" +
	"\x06events\x18\x05 \x01(\v2\".sui.rpc.v2beta2.TransactionEventsH\x03R\x06events\x88\x01\x01\x12#\n" +
	"\n" +
	"checkpoint\x18\x06 \x01(\x04H\x04R\n" +
	"checkpoint\x88\x01\x01\x12=\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x05R\ttimestamp\x88\x01\x01\x12G\n" +
	"\x0fbalance_changes\x18\b \x03(\v2\x1e.sui.rpc.v2beta2.BalanceChangeR\x0ebalanceChanges\x12<\n" +
	"\rinput_objects\x18\n" +
	" \x03(\v2\x17.sui.rpc.v2beta2.ObjectR\finputObjects\x12>\n" +
	"\x0eoutput_objects\x18\v \x03(\v2\x17.sui.rpc.v2beta2.ObjectR\routputObjectsB\t\n" +
	"\a_digestB\x0e\n" +
	"\f_transactionB\n" +
	"\n" +
	"\b_effectsB\t\n" +
	"\a_eventsB\r\n" +
	"\v_checkpointB\f\n" +
	"\n" +
	"_timestampb\x06proto3"

var (
	file_sui_rpc_v2beta2_executed_transaction_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta2_executed_transaction_proto_rawDescData []byte
)

func file_sui_rpc_v2beta2_executed_transaction_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta2_executed_transaction_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta2_executed_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_executed_transaction_proto_rawDesc), len(file_sui_rpc_v2beta2_executed_transaction_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta2_executed_transaction_proto_rawDescData
}

var file_sui_rpc_v2beta2_executed_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2beta2_executed_transaction_proto_goTypes = []any{
	(*ExecutedTransaction)(nil),   // 0: sui.rpc.v2beta2.ExecutedTransaction
	(*Transaction)(nil),           // 1: sui.rpc.v2beta2.Transaction
	(*UserSignature)(nil),         // 2: sui.rpc.v2beta2.UserSignature
	(*TransactionEffects)(nil),    // 3: sui.rpc.v2beta2.TransactionEffects
	(*TransactionEvents)(nil),     // 4: sui.rpc.v2beta2.TransactionEvents
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*BalanceChange)(nil),         // 6: sui.rpc.v2beta2.BalanceChange
	(*Object)(nil),                // 7: sui.rpc.v2beta2.Object
}
var file_sui_rpc_v2beta2_executed_transaction_proto_depIdxs = []int32{
	1, // 0: sui.rpc.v2beta2.ExecutedTransaction.transaction:type_name -> sui.rpc.v2beta2.Transaction
	2, // 1: sui.rpc.v2beta2.ExecutedTransaction.signatures:type_name -> sui.rpc.v2beta2.UserSignature
	3, // 2: sui.rpc.v2beta2.ExecutedTransaction.effects:type_name -> sui.rpc.v2beta2.TransactionEffects
	4, // 3: sui.rpc.v2beta2.ExecutedTransaction.events:type_name -> sui.rpc.v2beta2.TransactionEvents
	5, // 4: sui.rpc.v2beta2.ExecutedTransaction.timestamp:type_name -> google.protobuf.Timestamp
	6, // 5: sui.rpc.v2beta2.ExecutedTransaction.balance_changes:type_name -> sui.rpc.v2beta2.BalanceChange
	7, // 6: sui.rpc.v2beta2.ExecutedTransaction.input_objects:type_name -> sui.rpc.v2beta2.Object
	7, // 7: sui.rpc.v2beta2.ExecutedTransaction.output_objects:type_name -> sui.rpc.v2beta2.Object
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta2_executed_transaction_proto_init() }
func file_sui_rpc_v2beta2_executed_transaction_proto_init() {
	if File_sui_rpc_v2beta2_executed_transaction_proto != nil {
		return
	}
	file_sui_rpc_v2beta2_balance_change_proto_init()
	file_sui_rpc_v2beta2_effects_proto_init()
	file_sui_rpc_v2beta2_event_proto_init()
	file_sui_rpc_v2beta2_object_proto_init()
	file_sui_rpc_v2beta2_signature_proto_init()
	file_sui_rpc_v2beta2_transaction_proto_init()
	file_sui_rpc_v2beta2_executed_transaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_executed_transaction_proto_rawDesc), len(file_sui_rpc_v2beta2_executed_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2beta2_executed_transaction_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta2_executed_transaction_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2beta2_executed_transaction_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta2_executed_transaction_proto = out.File
	file_sui_rpc_v2beta2_executed_transaction_proto_goTypes = nil
	file_sui_rpc_v2beta2_executed_transaction_proto_depIdxs = nil
}
