// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.26.1
// source: sui/rpc/v2beta2/live_data_service.proto

package v2beta2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supply state of a coin, matching the Move SupplyState enum
type CoinTreasury_SupplyState int32

const (
	// Supply is unknown or TreasuryCap still exists (minting still possible)
	CoinTreasury_SUPPLY_STATE_UNKNOWN CoinTreasury_SupplyState = 0
	// Supply is fixed (TreasuryCap consumed, no more minting possible)
	CoinTreasury_FIXED CoinTreasury_SupplyState = 1
)

// Enum value maps for CoinTreasury_SupplyState.
var (
	CoinTreasury_SupplyState_name = map[int32]string{
		0: "SUPPLY_STATE_UNKNOWN",
		1: "FIXED",
	}
	CoinTreasury_SupplyState_value = map[string]int32{
		"SUPPLY_STATE_UNKNOWN": 0,
		"FIXED":                1,
	}
)

func (x CoinTreasury_SupplyState) Enum() *CoinTreasury_SupplyState {
	p := new(CoinTreasury_SupplyState)
	*p = x
	return p
}

func (x CoinTreasury_SupplyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinTreasury_SupplyState) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[0].Descriptor()
}

func (CoinTreasury_SupplyState) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[0]
}

func (x CoinTreasury_SupplyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinTreasury_SupplyState.Descriptor instead.
func (CoinTreasury_SupplyState) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{3, 0}
}

type DynamicField_DynamicFieldKind int32

const (
	DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN DynamicField_DynamicFieldKind = 0
	DynamicField_FIELD                      DynamicField_DynamicFieldKind = 1
	DynamicField_OBJECT                     DynamicField_DynamicFieldKind = 2
)

// Enum value maps for DynamicField_DynamicFieldKind.
var (
	DynamicField_DynamicFieldKind_name = map[int32]string{
		0: "DYNAMIC_FIELD_KIND_UNKNOWN",
		1: "FIELD",
		2: "OBJECT",
	}
	DynamicField_DynamicFieldKind_value = map[string]int32{
		"DYNAMIC_FIELD_KIND_UNKNOWN": 0,
		"FIELD":                      1,
		"OBJECT":                     2,
	}
)

func (x DynamicField_DynamicFieldKind) Enum() *DynamicField_DynamicFieldKind {
	p := new(DynamicField_DynamicFieldKind)
	*p = x
	return p
}

func (x DynamicField_DynamicFieldKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DynamicField_DynamicFieldKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[1].Descriptor()
}

func (DynamicField_DynamicFieldKind) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[1]
}

func (x DynamicField_DynamicFieldKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DynamicField_DynamicFieldKind.Descriptor instead.
func (DynamicField_DynamicFieldKind) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{12, 0}
}

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type SimulateTransactionRequest_TransactionChecks int32

const (
	SimulateTransactionRequest_ENABLED  SimulateTransactionRequest_TransactionChecks = 0
	SimulateTransactionRequest_DISABLED SimulateTransactionRequest_TransactionChecks = 1
)

// Enum value maps for SimulateTransactionRequest_TransactionChecks.
var (
	SimulateTransactionRequest_TransactionChecks_name = map[int32]string{
		0: "ENABLED",
		1: "DISABLED",
	}
	SimulateTransactionRequest_TransactionChecks_value = map[string]int32{
		"ENABLED":  0,
		"DISABLED": 1,
	}
)

func (x SimulateTransactionRequest_TransactionChecks) Enum() *SimulateTransactionRequest_TransactionChecks {
	p := new(SimulateTransactionRequest_TransactionChecks)
	*p = x
	return p
}

func (x SimulateTransactionRequest_TransactionChecks) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulateTransactionRequest_TransactionChecks) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[2].Descriptor()
}

func (SimulateTransactionRequest_TransactionChecks) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2beta2_live_data_service_proto_enumTypes[2]
}

func (x SimulateTransactionRequest_TransactionChecks) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulateTransactionRequest_TransactionChecks.Descriptor instead.
func (SimulateTransactionRequest_TransactionChecks) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{13, 0}
}

// Request message for `NodeService.GetCoinInfo`.
type GetCoinInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coin type to request information about
	CoinType      *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoinInfoRequest) Reset() {
	*x = GetCoinInfoRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoRequest) ProtoMessage() {}

func (x *GetCoinInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCoinInfoRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetCoinInfoRequest) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

// Response message for `NodeService.GetCoinInfo`.
type GetCoinInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The coin type.
	CoinType *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::CoinMetadata` if it exists and has not been wrapped.
	Metadata *CoinMetadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// This field will be populated with information about this coin
	// type's `0x2::coin::TreasuryCap` if it exists and has not been wrapped.
	Treasury *CoinTreasury `protobuf:"bytes,3,opt,name=treasury,proto3,oneof" json:"treasury,omitempty"`
	// If this coin type is a regulated coin, this field will be
	// populated with information about its `0x2::coin::RegulatedCoinMetadata`
	// object.
	RegulatedMetadata *RegulatedCoinMetadata `protobuf:"bytes,4,opt,name=regulated_metadata,json=regulatedMetadata,proto3,oneof" json:"regulated_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCoinInfoResponse) Reset() {
	*x = GetCoinInfoResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoinInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinInfoResponse) ProtoMessage() {}

func (x *GetCoinInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCoinInfoResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCoinInfoResponse) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *GetCoinInfoResponse) GetMetadata() *CoinMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GetCoinInfoResponse) GetTreasury() *CoinTreasury {
	if x != nil {
		return x.Treasury
	}
	return nil
}

func (x *GetCoinInfoResponse) GetRegulatedMetadata() *RegulatedCoinMetadata {
	if x != nil {
		return x.RegulatedMetadata
	}
	return nil
}

// Metadata for a coin type
type CoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::CoinMetadata` object or
	// 0x2::sui::coin_registry::CoinData object (when registered with CoinRegistry).
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Number of decimal places to coin uses.
	Decimals *uint32 `protobuf:"varint,2,opt,name=decimals,proto3,oneof" json:"decimals,omitempty"`
	// Name for the token
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Symbol for the token
	Symbol *string `protobuf:"bytes,4,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	// Description of the token
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// URL for the token logo
	IconUrl *string `protobuf:"bytes,6,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	// The MetadataCap ID if it has been claimed for this coin type.
	// This capability allows updating the coin's metadata fields.
	// Only populated when metadata is from CoinRegistry.
	MetadataCapId *string `protobuf:"bytes,7,opt,name=metadata_cap_id,json=metadataCapId,proto3,oneof" json:"metadata_cap_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinMetadata) Reset() {
	*x = CoinMetadata{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinMetadata) ProtoMessage() {}

func (x *CoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinMetadata.ProtoReflect.Descriptor instead.
func (*CoinMetadata) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{2}
}

func (x *CoinMetadata) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CoinMetadata) GetDecimals() uint32 {
	if x != nil && x.Decimals != nil {
		return *x.Decimals
	}
	return 0
}

func (x *CoinMetadata) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CoinMetadata) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *CoinMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CoinMetadata) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *CoinMetadata) GetMetadataCapId() string {
	if x != nil && x.MetadataCapId != nil {
		return *x.MetadataCapId
	}
	return ""
}

// Information about a coin type's `0x2::coin::TreasuryCap` and its total available supply
type CoinTreasury struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::TreasuryCap` object.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Total available supply for this coin type.
	TotalSupply *uint64 `protobuf:"varint,2,opt,name=total_supply,json=totalSupply,proto3,oneof" json:"total_supply,omitempty"`
	// Supply state indicating if the supply is fixed or can still be minted
	SupplyState   *CoinTreasury_SupplyState `protobuf:"varint,3,opt,name=supply_state,json=supplyState,proto3,enum=sui.rpc.v2beta2.CoinTreasury_SupplyState,oneof" json:"supply_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoinTreasury) Reset() {
	*x = CoinTreasury{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoinTreasury) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinTreasury) ProtoMessage() {}

func (x *CoinTreasury) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinTreasury.ProtoReflect.Descriptor instead.
func (*CoinTreasury) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{3}
}

func (x *CoinTreasury) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CoinTreasury) GetTotalSupply() uint64 {
	if x != nil && x.TotalSupply != nil {
		return *x.TotalSupply
	}
	return 0
}

func (x *CoinTreasury) GetSupplyState() CoinTreasury_SupplyState {
	if x != nil && x.SupplyState != nil {
		return *x.SupplyState
	}
	return CoinTreasury_SUPPLY_STATE_UNKNOWN
}

// Information about a regulated coin, which indicates that it makes use of the transfer deny list.
type RegulatedCoinMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectId of the `0x2::coin::RegulatedCoinMetadata` object.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The ID of the coin's `CoinMetadata` or `CoinData` object.
	CoinMetadataObject *string `protobuf:"bytes,2,opt,name=coin_metadata_object,json=coinMetadataObject,proto3,oneof" json:"coin_metadata_object,omitempty"`
	// The ID of the coin's `DenyCap` object.
	DenyCapObject *string `protobuf:"bytes,3,opt,name=deny_cap_object,json=denyCapObject,proto3,oneof" json:"deny_cap_object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegulatedCoinMetadata) Reset() {
	*x = RegulatedCoinMetadata{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegulatedCoinMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegulatedCoinMetadata) ProtoMessage() {}

func (x *RegulatedCoinMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegulatedCoinMetadata.ProtoReflect.Descriptor instead.
func (*RegulatedCoinMetadata) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{4}
}

func (x *RegulatedCoinMetadata) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RegulatedCoinMetadata) GetCoinMetadataObject() string {
	if x != nil && x.CoinMetadataObject != nil {
		return *x.CoinMetadataObject
	}
	return ""
}

func (x *RegulatedCoinMetadata) GetDenyCapObject() string {
	if x != nil && x.DenyCapObject != nil {
		return *x.DenyCapObject
	}
	return ""
}

// Request message for `LiveDataService.GetBalance`.
type GetBalanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The owner's Sui address.
	Owner *string `protobuf:"bytes,1,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// Required. The type names for the coin (e.g., 0x2::sui::SUI).
	CoinType      *string `protobuf:"bytes,2,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetBalanceRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *GetBalanceRequest) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

// Response message for `LiveDataService.GetBalance`.
// Return the total coin balance for one coin type, owned by the address owner.
type GetBalanceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The balance information for the requested coin type.
	Balance       *Balance `protobuf:"bytes,1,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

// Request message for `LiveDataService.ListBalances`.
type ListBalancesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The owner's Sui address.
	Owner *string `protobuf:"bytes,1,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// The maximum number of balance entries to return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListBalances` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListBalances` must
	// match the call that provided the page token.
	PageToken     []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesRequest) Reset() {
	*x = ListBalancesRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesRequest) ProtoMessage() {}

func (x *ListBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesRequest.ProtoReflect.Descriptor instead.
func (*ListBalancesRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListBalancesRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *ListBalancesRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListBalancesRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

// Response message for `LiveDataService.ListBalances`.
// Return the total coin balance for all coin types, owned by the address owner.
type ListBalancesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of coin types and their respective balances.
	Balances []*Balance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesResponse) Reset() {
	*x = ListBalancesResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesResponse) ProtoMessage() {}

func (x *ListBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesResponse.ProtoReflect.Descriptor instead.
func (*ListBalancesResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *ListBalancesResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

// Balance information for a specific coin type.
type Balance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the coin (e.g., 0x2::sui::SUI).
	CoinType *string `protobuf:"bytes,1,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// Shows the total balance of the coin in its smallest unit.
	Balance       *uint64 `protobuf:"varint,3,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{9}
}

func (x *Balance) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *Balance) GetBalance() uint64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

// Request message for `NodeService.ListDynamicFields`
type ListDynamicFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The `UID` of the parent, which owns the collections of dynamic fields.
	Parent *string `protobuf:"bytes,1,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// The maximum number of dynamic fields to return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListDynamicFields` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListDynamicFields` must
	// match the call that provided the page token.
	PageToken []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `parent,field_id`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDynamicFieldsRequest) Reset() {
	*x = ListDynamicFieldsRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsRequest) ProtoMessage() {}

func (x *ListDynamicFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsRequest.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListDynamicFieldsRequest) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *ListDynamicFieldsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListDynamicFieldsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListDynamicFieldsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response message for `NodeService.ListDynamicFields`
type ListDynamicFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page of dynamic fields owned by the specified parent.
	DynamicFields []*DynamicField `protobuf:"bytes,1,rep,name=dynamic_fields,json=dynamicFields,proto3" json:"dynamic_fields,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDynamicFieldsResponse) Reset() {
	*x = ListDynamicFieldsResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDynamicFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDynamicFieldsResponse) ProtoMessage() {}

func (x *ListDynamicFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDynamicFieldsResponse.ProtoReflect.Descriptor instead.
func (*ListDynamicFieldsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListDynamicFieldsResponse) GetDynamicFields() []*DynamicField {
	if x != nil {
		return x.DynamicFields
	}
	return nil
}

func (x *ListDynamicFieldsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type DynamicField struct {
	state protoimpl.MessageState         `protogen:"open.v1"`
	Kind  *DynamicField_DynamicFieldKind `protobuf:"varint,1,opt,name=kind,proto3,enum=sui.rpc.v2beta2.DynamicField_DynamicFieldKind,oneof" json:"kind,omitempty"`
	// ObjectId of this dynamic field's parent.
	Parent *string `protobuf:"bytes,2,opt,name=parent,proto3,oneof" json:"parent,omitempty"`
	// ObjectId of this dynamic field.
	FieldId *string `protobuf:"bytes,3,opt,name=field_id,json=fieldId,proto3,oneof" json:"field_id,omitempty"`
	// The type of the dynamic field "name"
	NameType *string `protobuf:"bytes,4,opt,name=name_type,json=nameType,proto3,oneof" json:"name_type,omitempty"`
	// The serialized move value of "name"
	NameValue []byte `protobuf:"bytes,5,opt,name=name_value,json=nameValue,proto3,oneof" json:"name_value,omitempty"`
	// The type of the dynamic field "value".
	//
	// If this is a dynamic object field then this is the type of the object
	// itself (which is a child of this field), otherwise this is the type of the
	// value of this field.
	ValueType *string `protobuf:"bytes,6,opt,name=value_type,json=valueType,proto3,oneof" json:"value_type,omitempty"`
	// The ObjectId of the child object when a child is a dynamic
	// object field.
	//
	// The presence or absence of this field can be used to determine if a child
	// is a dynamic field or a dynamic child object
	DynamicObjectId *string `protobuf:"bytes,7,opt,name=dynamic_object_id,json=dynamicObjectId,proto3,oneof" json:"dynamic_object_id,omitempty"`
	// The object itself when a child is a dynamic object field.
	Object        *Object `protobuf:"bytes,8,opt,name=object,proto3,oneof" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicField) Reset() {
	*x = DynamicField{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicField) ProtoMessage() {}

func (x *DynamicField) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicField.ProtoReflect.Descriptor instead.
func (*DynamicField) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{12}
}

func (x *DynamicField) GetKind() DynamicField_DynamicFieldKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return DynamicField_DYNAMIC_FIELD_KIND_UNKNOWN
}

func (x *DynamicField) GetParent() string {
	if x != nil && x.Parent != nil {
		return *x.Parent
	}
	return ""
}

func (x *DynamicField) GetFieldId() string {
	if x != nil && x.FieldId != nil {
		return *x.FieldId
	}
	return ""
}

func (x *DynamicField) GetNameType() string {
	if x != nil && x.NameType != nil {
		return *x.NameType
	}
	return ""
}

func (x *DynamicField) GetNameValue() []byte {
	if x != nil {
		return x.NameValue
	}
	return nil
}

func (x *DynamicField) GetValueType() string {
	if x != nil && x.ValueType != nil {
		return *x.ValueType
	}
	return ""
}

func (x *DynamicField) GetDynamicObjectId() string {
	if x != nil && x.DynamicObjectId != nil {
		return *x.DynamicObjectId
	}
	return ""
}

func (x *DynamicField) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type SimulateTransactionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// Mask specifying which fields to read.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Specify whether checks should be ENABLED (default) or DISABLED while executing the transaction
	Checks *SimulateTransactionRequest_TransactionChecks `protobuf:"varint,3,opt,name=checks,proto3,enum=sui.rpc.v2beta2.SimulateTransactionRequest_TransactionChecks,oneof" json:"checks,omitempty"`
	// Perform gas selection based on a budget estimation and include the
	// selected gas payment and budget in the response.
	//
	// This option will be ignored if `checks` is `DISABLED`.
	DoGasSelection *bool `protobuf:"varint,4,opt,name=do_gas_selection,json=doGasSelection,proto3,oneof" json:"do_gas_selection,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulateTransactionRequest) Reset() {
	*x = SimulateTransactionRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionRequest) ProtoMessage() {}

func (x *SimulateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionRequest.ProtoReflect.Descriptor instead.
func (*SimulateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{13}
}

func (x *SimulateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *SimulateTransactionRequest) GetChecks() SimulateTransactionRequest_TransactionChecks {
	if x != nil && x.Checks != nil {
		return *x.Checks
	}
	return SimulateTransactionRequest_ENABLED
}

func (x *SimulateTransactionRequest) GetDoGasSelection() bool {
	if x != nil && x.DoGasSelection != nil {
		return *x.DoGasSelection
	}
	return false
}

type SimulateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *ExecutedTransaction   `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	Outputs       []*CommandResult       `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionResponse) Reset() {
	*x = SimulateTransactionResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionResponse) ProtoMessage() {}

func (x *SimulateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionResponse.ProtoReflect.Descriptor instead.
func (*SimulateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{14}
}

func (x *SimulateTransactionResponse) GetTransaction() *ExecutedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionResponse) GetOutputs() []*CommandResult {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// An intermediate result/output from the execution of a single command
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnValues  []*CommandOutput       `protobuf:"bytes,1,rep,name=return_values,json=returnValues,proto3" json:"return_values,omitempty"`
	MutatedByRef  []*CommandOutput       `protobuf:"bytes,2,rep,name=mutated_by_ref,json=mutatedByRef,proto3" json:"mutated_by_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{15}
}

func (x *CommandResult) GetReturnValues() []*CommandOutput {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

func (x *CommandResult) GetMutatedByRef() []*CommandOutput {
	if x != nil {
		return x.MutatedByRef
	}
	return nil
}

type CommandOutput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Argument *Argument              `protobuf:"bytes,1,opt,name=argument,proto3,oneof" json:"argument,omitempty"`
	Value    *Bcs                   `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// JSON rendering of the output.
	Json          *structpb.Value `protobuf:"bytes,3,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{16}
}

func (x *CommandOutput) GetArgument() *Argument {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *CommandOutput) GetValue() *Bcs {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CommandOutput) GetJson() *structpb.Value {
	if x != nil {
		return x.Json
	}
	return nil
}

type ListOwnedObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The address of the account that owns the objects.
	Owner *string `protobuf:"bytes,1,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	// The maximum number of entries return. The service may return fewer than this value.
	// If unspecified, at most `50` entries will be returned.
	// The maximum value is `1000`; values above `1000` will be coerced to `1000`.
	PageSize *uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// A page token, received from a previous `ListOwnedObjects` call.
	// Provide this to retrieve the subsequent page.
	//
	// When paginating, all other parameters provided to `ListOwnedObjects` must
	// match the call that provided the page token.
	PageToken []byte `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `object_id,version,object_type`.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Optional type filter to limit the types of objects listed.
	//
	// Providing an object type with no type params will return objects of that
	// type with any type parameter, e.g. `0x2::coin::Coin` will return all
	// `Coin<T>` objects regardless of the type parameter `T`. Providing a type
	// with a type param will retrict the returned objects to only those objects
	// that match the provided type parameters, e.g.
	// `0x2::coin::Coin<0x2::sui::SUI>` will only return `Coin<SUI>` objects.
	ObjectType    *string `protobuf:"bytes,5,opt,name=object_type,json=objectType,proto3,oneof" json:"object_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedObjectsRequest) Reset() {
	*x = ListOwnedObjectsRequest{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsRequest) ProtoMessage() {}

func (x *ListOwnedObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListOwnedObjectsRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *ListOwnedObjectsRequest) GetPageSize() uint32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListOwnedObjectsRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ListOwnedObjectsRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *ListOwnedObjectsRequest) GetObjectType() string {
	if x != nil && x.ObjectType != nil {
		return *x.ObjectType
	}
	return ""
}

type ListOwnedObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page of dynamic fields owned by the specified parent.
	Objects []*Object `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOwnedObjectsResponse) Reset() {
	*x = ListOwnedObjectsResponse{}
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOwnedObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOwnedObjectsResponse) ProtoMessage() {}

func (x *ListOwnedObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOwnedObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListOwnedObjectsResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListOwnedObjectsResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListOwnedObjectsResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

var File_sui_rpc_v2beta2_live_data_service_proto protoreflect.FileDescriptor

const file_sui_rpc_v2beta2_live_data_service_proto_rawDesc = "" +
	"\n" +
	"'sui/rpc/v2beta2/live_data_service.proto\x12\x0fsui.rpc.v2beta2\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1esui/rpc/v2beta2/argument.proto\x1a\x19sui/rpc/v2beta2/bcs.proto\x1a*sui/rpc/v2beta2/executed_transaction.proto\x1a\x1csui/rpc/v2beta2/object.proto\x1a!sui/rpc/v2beta2/transaction.proto\"D\n" +
	"\x12GetCoinInfoRequest\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01B\f\n" +
	"\n" +
	"_coin_type\"\xd2\x02\n" +
	"\x13GetCoinInfoResponse\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01\x12>\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1d.sui.rpc.v2beta2.CoinMetadataH\x01R\bmetadata\x88\x01\x01\x12>\n" +
	"\btreasury\x18\x03 \x01(\v2\x1d.sui.rpc.v2beta2.CoinTreasuryH\x02R\btreasury\x88\x01\x01\x12Z\n" +
	"\x12regulated_metadata\x18\x04 \x01(\v2&.sui.rpc.v2beta2.RegulatedCoinMetadataH\x03R\x11regulatedMetadata\x88\x01\x01B\f\n" +
	"\n" +
	"_coin_typeB\v\n" +
	"\t_metadataB\v\n" +
	"\t_treasuryB\x15\n" +
	"\x13_regulated_metadata\"\xc7\x02\n" +
	"\fCoinMetadata\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x1f\n" +
	"\bdecimals\x18\x02 \x01(\rH\x01R\bdecimals\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x02R\x04name\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x04 \x01(\tH\x03R\x06symbol\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x04R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\x06 \x01(\tH\x05R\aiconUrl\x88\x01\x01\x12+\n" +
	"\x0fmetadata_cap_id\x18\a \x01(\tH\x06R\rmetadataCapId\x88\x01\x01B\x05\n" +
	"\x03_idB\v\n" +
	"\t_decimalsB\a\n" +
	"\x05_nameB\t\n" +
	"\a_symbolB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_icon_urlB\x12\n" +
	"\x10_metadata_cap_id\"\xfb\x01\n" +
	"\fCoinTreasury\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12&\n" +
	"\ftotal_supply\x18\x02 \x01(\x04H\x01R\vtotalSupply\x88\x01\x01\x12Q\n" +
	"\fsupply_state\x18\x03 \x01(\x0e2).sui.rpc.v2beta2.CoinTreasury.SupplyStateH\x02R\vsupplyState\x88\x01\x01\"2\n" +
	"\vSupplyState\x12\x18\n" +
	"\x14SUPPLY_STATE_UNKNOWN\x10\x00\x12\t\n" +
	"\x05FIXED\x10\x01B\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_total_supplyB\x0f\n" +
	"\r_supply_state\"\xc4\x01\n" +
	"\x15RegulatedCoinMetadata\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x125\n" +
	"\x14coin_metadata_object\x18\x02 \x01(\tH\x01R\x12coinMetadataObject\x88\x01\x01\x12+\n" +
	"\x0fdeny_cap_object\x18\x03 \x01(\tH\x02R\rdenyCapObject\x88\x01\x01B\x05\n" +
	"\x03_idB\x17\n" +
	"\x15_coin_metadata_objectB\x12\n" +
	"\x10_deny_cap_object\"h\n" +
	"\x11GetBalanceRequest\x12\x19\n" +
	"\x05owner\x18\x01 \x01(\tH\x00R\x05owner\x88\x01\x01\x12 \n" +
	"\tcoin_type\x18\x02 \x01(\tH\x01R\bcoinType\x88\x01\x01B\b\n" +
	"\x06_ownerB\f\n" +
	"\n" +
	"_coin_type\"Y\n" +
	"\x12GetBalanceResponse\x127\n" +
	"\abalance\x18\x01 \x01(\v2\x18.sui.rpc.v2beta2.BalanceH\x00R\abalance\x88\x01\x01B\n" +
	"\n" +
	"\b_balance\"\x9d\x01\n" +
	"\x13ListBalancesRequest\x12\x19\n" +
	"\x05owner\x18\x01 \x01(\tH\x00R\x05owner\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_ownerB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8d\x01\n" +
	"\x14ListBalancesResponse\x124\n" +
	"\bbalances\x18\x01 \x03(\v2\x18.sui.rpc.v2beta2.BalanceR\bbalances\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"d\n" +
	"\aBalance\x12 \n" +
	"\tcoin_type\x18\x01 \x01(\tH\x00R\bcoinType\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x03 \x01(\x04H\x01R\abalance\x88\x01\x01B\f\n" +
	"\n" +
	"_coin_typeB\n" +
	"\n" +
	"\b_balance\"\xf1\x01\n" +
	"\x18ListDynamicFieldsRequest\x12\x1b\n" +
	"\x06parent\x18\x01 \x01(\tH\x00R\x06parent\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskH\x03R\breadMask\x88\x01\x01B\t\n" +
	"\a_parentB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\f\n" +
	"\n" +
	"_read_mask\"\xa2\x01\n" +
	"\x19ListDynamicFieldsResponse\x12D\n" +
	"\x0edynamic_fields\x18\x01 \x03(\v2\x1d.sui.rpc.v2beta2.DynamicFieldR\rdynamicFields\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"\x9e\x04\n" +
	"\fDynamicField\x12G\n" +
	"\x04kind\x18\x01 \x01(\x0e2..sui.rpc.v2beta2.DynamicField.DynamicFieldKindH\x00R\x04kind\x88\x01\x01\x12\x1b\n" +
	"\x06parent\x18\x02 \x01(\tH\x01R\x06parent\x88\x01\x01\x12\x1e\n" +
	"\bfield_id\x18\x03 \x01(\tH\x02R\afieldId\x88\x01\x01\x12 \n" +
	"\tname_type\x18\x04 \x01(\tH\x03R\bnameType\x88\x01\x01\x12\"\n" +
	"\n" +
	"name_value\x18\x05 \x01(\fH\x04R\tnameValue\x88\x01\x01\x12\"\n" +
	"\n" +
	"value_type\x18\x06 \x01(\tH\x05R\tvalueType\x88\x01\x01\x12/\n" +
	"\x11dynamic_object_id\x18\a \x01(\tH\x06R\x0fdynamicObjectId\x88\x01\x01\x124\n" +
	"\x06object\x18\b \x01(\v2\x17.sui.rpc.v2beta2.ObjectH\aR\x06object\x88\x01\x01\"I\n" +
	"\x10DynamicFieldKind\x12\x1e\n" +
	"\x1aDYNAMIC_FIELD_KIND_UNKNOWN\x10\x00\x12\t\n" +
	"\x05FIELD\x10\x01\x12\n" +
	"\n" +
	"\x06OBJECT\x10\x02B\a\n" +
	"\x05_kindB\t\n" +
	"\a_parentB\v\n" +
	"\t_field_idB\f\n" +
	"\n" +
	"_name_typeB\r\n" +
	"\v_name_valueB\r\n" +
	"\v_value_typeB\x14\n" +
	"\x12_dynamic_object_idB\t\n" +
	"\a_object\"\x98\x03\n" +
	"\x1aSimulateTransactionRequest\x12C\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1c.sui.rpc.v2beta2.TransactionH\x00R\vtransaction\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01\x12Z\n" +
	"\x06checks\x18\x03 \x01(\x0e2=.sui.rpc.v2beta2.SimulateTransactionRequest.TransactionChecksH\x02R\x06checks\x88\x01\x01\x12-\n" +
	"\x10do_gas_selection\x18\x04 \x01(\bH\x03R\x0edoGasSelection\x88\x01\x01\".\n" +
	"\x11TransactionChecks\x12\v\n" +
	"\aENABLED\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01B\x0e\n" +
	"\f_transactionB\f\n" +
	"\n" +
	"_read_maskB\t\n" +
	"\a_checksB\x13\n" +
	"\x11_do_gas_selection\"\xb4\x01\n" +
	"\x1bSimulateTransactionResponse\x12K\n" +
	"\vtransaction\x18\x01 \x01(\v2$.sui.rpc.v2beta2.ExecutedTransactionH\x00R\vtransaction\x88\x01\x01\x128\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1e.sui.rpc.v2beta2.CommandResultR\aoutputsB\x0e\n" +
	"\f_transaction\"\x9a\x01\n" +
	"\rCommandResult\x12C\n" +
	"\rreturn_values\x18\x01 \x03(\v2\x1e.sui.rpc.v2beta2.CommandOutputR\freturnValues\x12D\n" +
	"\x0emutated_by_ref\x18\x02 \x03(\v2\x1e.sui.rpc.v2beta2.CommandOutputR\fmutatedByRef\"\xcd\x01\n" +
	"\rCommandOutput\x12:\n" +
	"\bargument\x18\x01 \x01(\v2\x19.sui.rpc.v2beta2.ArgumentH\x00R\bargument\x88\x01\x01\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x14.sui.rpc.v2beta2.BcsH\x01R\x05value\x88\x01\x01\x12/\n" +
	"\x04json\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x02R\x04json\x88\x01\x01B\v\n" +
	"\t_argumentB\b\n" +
	"\x06_valueB\a\n" +
	"\x05_json\"\xa3\x02\n" +
	"\x17ListOwnedObjectsRequest\x12\x19\n" +
	"\x05owner\x18\x01 \x01(\tH\x00R\x05owner\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\rH\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x03 \x01(\fH\x02R\tpageToken\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskH\x03R\breadMask\x88\x01\x01\x12$\n" +
	"\vobject_type\x18\x05 \x01(\tH\x04R\n" +
	"objectType\x88\x01\x01B\b\n" +
	"\x06_ownerB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_tokenB\f\n" +
	"\n" +
	"_read_maskB\x0e\n" +
	"\f_object_type\"\x8e\x01\n" +
	"\x18ListOwnedObjectsResponse\x121\n" +
	"\aobjects\x18\x01 \x03(\v2\x17.sui.rpc.v2beta2.ObjectR\aobjects\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token2\xe6\x04\n" +
	"\x0fLiveDataService\x12j\n" +
	"\x11ListDynamicFields\x12).sui.rpc.v2beta2.ListDynamicFieldsRequest\x1a*.sui.rpc.v2beta2.ListDynamicFieldsResponse\x12g\n" +
	"\x10ListOwnedObjects\x12(.sui.rpc.v2beta2.ListOwnedObjectsRequest\x1a).sui.rpc.v2beta2.ListOwnedObjectsResponse\x12X\n" +
	"\vGetCoinInfo\x12#.sui.rpc.v2beta2.GetCoinInfoRequest\x1a$.sui.rpc.v2beta2.GetCoinInfoResponse\x12U\n" +
	"\n" +
	"GetBalance\x12\".sui.rpc.v2beta2.GetBalanceRequest\x1a#.sui.rpc.v2beta2.GetBalanceResponse\x12[\n" +
	"\fListBalances\x12$.sui.rpc.v2beta2.ListBalancesRequest\x1a%.sui.rpc.v2beta2.ListBalancesResponse\x12p\n" +
	"\x13SimulateTransaction\x12+.sui.rpc.v2beta2.SimulateTransactionRequest\x1a,.sui.rpc.v2beta2.SimulateTransactionResponseb\x06proto3"

var (
	file_sui_rpc_v2beta2_live_data_service_proto_rawDescOnce sync.Once
	file_sui_rpc_v2beta2_live_data_service_proto_rawDescData []byte
)

func file_sui_rpc_v2beta2_live_data_service_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2beta2_live_data_service_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2beta2_live_data_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_live_data_service_proto_rawDesc), len(file_sui_rpc_v2beta2_live_data_service_proto_rawDesc)))
	})
	return file_sui_rpc_v2beta2_live_data_service_proto_rawDescData
}

var file_sui_rpc_v2beta2_live_data_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sui_rpc_v2beta2_live_data_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_sui_rpc_v2beta2_live_data_service_proto_goTypes = []any{
	(CoinTreasury_SupplyState)(0),                     // 0: sui.rpc.v2beta2.CoinTreasury.SupplyState
	(DynamicField_DynamicFieldKind)(0),                // 1: sui.rpc.v2beta2.DynamicField.DynamicFieldKind
	(SimulateTransactionRequest_TransactionChecks)(0), // 2: sui.rpc.v2beta2.SimulateTransactionRequest.TransactionChecks
	(*GetCoinInfoRequest)(nil),                        // 3: sui.rpc.v2beta2.GetCoinInfoRequest
	(*GetCoinInfoResponse)(nil),                       // 4: sui.rpc.v2beta2.GetCoinInfoResponse
	(*CoinMetadata)(nil),                              // 5: sui.rpc.v2beta2.CoinMetadata
	(*CoinTreasury)(nil),                              // 6: sui.rpc.v2beta2.CoinTreasury
	(*RegulatedCoinMetadata)(nil),                     // 7: sui.rpc.v2beta2.RegulatedCoinMetadata
	(*GetBalanceRequest)(nil),                         // 8: sui.rpc.v2beta2.GetBalanceRequest
	(*GetBalanceResponse)(nil),                        // 9: sui.rpc.v2beta2.GetBalanceResponse
	(*ListBalancesRequest)(nil),                       // 10: sui.rpc.v2beta2.ListBalancesRequest
	(*ListBalancesResponse)(nil),                      // 11: sui.rpc.v2beta2.ListBalancesResponse
	(*Balance)(nil),                                   // 12: sui.rpc.v2beta2.Balance
	(*ListDynamicFieldsRequest)(nil),                  // 13: sui.rpc.v2beta2.ListDynamicFieldsRequest
	(*ListDynamicFieldsResponse)(nil),                 // 14: sui.rpc.v2beta2.ListDynamicFieldsResponse
	(*DynamicField)(nil),                              // 15: sui.rpc.v2beta2.DynamicField
	(*SimulateTransactionRequest)(nil),                // 16: sui.rpc.v2beta2.SimulateTransactionRequest
	(*SimulateTransactionResponse)(nil),               // 17: sui.rpc.v2beta2.SimulateTransactionResponse
	(*CommandResult)(nil),                             // 18: sui.rpc.v2beta2.CommandResult
	(*CommandOutput)(nil),                             // 19: sui.rpc.v2beta2.CommandOutput
	(*ListOwnedObjectsRequest)(nil),                   // 20: sui.rpc.v2beta2.ListOwnedObjectsRequest
	(*ListOwnedObjectsResponse)(nil),                  // 21: sui.rpc.v2beta2.ListOwnedObjectsResponse
	(*fieldmaskpb.FieldMask)(nil),                     // 22: google.protobuf.FieldMask
	(*Object)(nil),                                    // 23: sui.rpc.v2beta2.Object
	(*Transaction)(nil),                               // 24: sui.rpc.v2beta2.Transaction
	(*ExecutedTransaction)(nil),                       // 25: sui.rpc.v2beta2.ExecutedTransaction
	(*Argument)(nil),                                  // 26: sui.rpc.v2beta2.Argument
	(*Bcs)(nil),                                       // 27: sui.rpc.v2beta2.Bcs
	(*structpb.Value)(nil),                            // 28: google.protobuf.Value
}
var file_sui_rpc_v2beta2_live_data_service_proto_depIdxs = []int32{
	5,  // 0: sui.rpc.v2beta2.GetCoinInfoResponse.metadata:type_name -> sui.rpc.v2beta2.CoinMetadata
	6,  // 1: sui.rpc.v2beta2.GetCoinInfoResponse.treasury:type_name -> sui.rpc.v2beta2.CoinTreasury
	7,  // 2: sui.rpc.v2beta2.GetCoinInfoResponse.regulated_metadata:type_name -> sui.rpc.v2beta2.RegulatedCoinMetadata
	0,  // 3: sui.rpc.v2beta2.CoinTreasury.supply_state:type_name -> sui.rpc.v2beta2.CoinTreasury.SupplyState
	12, // 4: sui.rpc.v2beta2.GetBalanceResponse.balance:type_name -> sui.rpc.v2beta2.Balance
	12, // 5: sui.rpc.v2beta2.ListBalancesResponse.balances:type_name -> sui.rpc.v2beta2.Balance
	22, // 6: sui.rpc.v2beta2.ListDynamicFieldsRequest.read_mask:type_name -> google.protobuf.FieldMask
	15, // 7: sui.rpc.v2beta2.ListDynamicFieldsResponse.dynamic_fields:type_name -> sui.rpc.v2beta2.DynamicField
	1,  // 8: sui.rpc.v2beta2.DynamicField.kind:type_name -> sui.rpc.v2beta2.DynamicField.DynamicFieldKind
	23, // 9: sui.rpc.v2beta2.DynamicField.object:type_name -> sui.rpc.v2beta2.Object
	24, // 10: sui.rpc.v2beta2.SimulateTransactionRequest.transaction:type_name -> sui.rpc.v2beta2.Transaction
	22, // 11: sui.rpc.v2beta2.SimulateTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	2,  // 12: sui.rpc.v2beta2.SimulateTransactionRequest.checks:type_name -> sui.rpc.v2beta2.SimulateTransactionRequest.TransactionChecks
	25, // 13: sui.rpc.v2beta2.SimulateTransactionResponse.transaction:type_name -> sui.rpc.v2beta2.ExecutedTransaction
	18, // 14: sui.rpc.v2beta2.SimulateTransactionResponse.outputs:type_name -> sui.rpc.v2beta2.CommandResult
	19, // 15: sui.rpc.v2beta2.CommandResult.return_values:type_name -> sui.rpc.v2beta2.CommandOutput
	19, // 16: sui.rpc.v2beta2.CommandResult.mutated_by_ref:type_name -> sui.rpc.v2beta2.CommandOutput
	26, // 17: sui.rpc.v2beta2.CommandOutput.argument:type_name -> sui.rpc.v2beta2.Argument
	27, // 18: sui.rpc.v2beta2.CommandOutput.value:type_name -> sui.rpc.v2beta2.Bcs
	28, // 19: sui.rpc.v2beta2.CommandOutput.json:type_name -> google.protobuf.Value
	22, // 20: sui.rpc.v2beta2.ListOwnedObjectsRequest.read_mask:type_name -> google.protobuf.FieldMask
	23, // 21: sui.rpc.v2beta2.ListOwnedObjectsResponse.objects:type_name -> sui.rpc.v2beta2.Object
	13, // 22: sui.rpc.v2beta2.LiveDataService.ListDynamicFields:input_type -> sui.rpc.v2beta2.ListDynamicFieldsRequest
	20, // 23: sui.rpc.v2beta2.LiveDataService.ListOwnedObjects:input_type -> sui.rpc.v2beta2.ListOwnedObjectsRequest
	3,  // 24: sui.rpc.v2beta2.LiveDataService.GetCoinInfo:input_type -> sui.rpc.v2beta2.GetCoinInfoRequest
	8,  // 25: sui.rpc.v2beta2.LiveDataService.GetBalance:input_type -> sui.rpc.v2beta2.GetBalanceRequest
	10, // 26: sui.rpc.v2beta2.LiveDataService.ListBalances:input_type -> sui.rpc.v2beta2.ListBalancesRequest
	16, // 27: sui.rpc.v2beta2.LiveDataService.SimulateTransaction:input_type -> sui.rpc.v2beta2.SimulateTransactionRequest
	14, // 28: sui.rpc.v2beta2.LiveDataService.ListDynamicFields:output_type -> sui.rpc.v2beta2.ListDynamicFieldsResponse
	21, // 29: sui.rpc.v2beta2.LiveDataService.ListOwnedObjects:output_type -> sui.rpc.v2beta2.ListOwnedObjectsResponse
	4,  // 30: sui.rpc.v2beta2.LiveDataService.GetCoinInfo:output_type -> sui.rpc.v2beta2.GetCoinInfoResponse
	9,  // 31: sui.rpc.v2beta2.LiveDataService.GetBalance:output_type -> sui.rpc.v2beta2.GetBalanceResponse
	11, // 32: sui.rpc.v2beta2.LiveDataService.ListBalances:output_type -> sui.rpc.v2beta2.ListBalancesResponse
	17, // 33: sui.rpc.v2beta2.LiveDataService.SimulateTransaction:output_type -> sui.rpc.v2beta2.SimulateTransactionResponse
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2beta2_live_data_service_proto_init() }
func file_sui_rpc_v2beta2_live_data_service_proto_init() {
	if File_sui_rpc_v2beta2_live_data_service_proto != nil {
		return
	}
	file_sui_rpc_v2beta2_argument_proto_init()
	file_sui_rpc_v2beta2_bcs_proto_init()
	file_sui_rpc_v2beta2_executed_transaction_proto_init()
	file_sui_rpc_v2beta2_object_proto_init()
	file_sui_rpc_v2beta2_transaction_proto_init()
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[16].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_sui_rpc_v2beta2_live_data_service_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2beta2_live_data_service_proto_rawDesc), len(file_sui_rpc_v2beta2_live_data_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sui_rpc_v2beta2_live_data_service_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2beta2_live_data_service_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2beta2_live_data_service_proto_enumTypes,
		MessageInfos:      file_sui_rpc_v2beta2_live_data_service_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2beta2_live_data_service_proto = out.File
	file_sui_rpc_v2beta2_live_data_service_proto_goTypes = nil
	file_sui_rpc_v2beta2_live_data_service_proto_depIdxs = nil
}
