// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/bcs.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// `Bcs` contains an arbitrary type that is serialized using the
// [BCS](https://mystenlabs.github.io/sui-rust-sdk/sui_sdk_types/index.html#bcs)
// format as well as a name that identifies the type of the serialized value.
type Bcs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name that identifies the type of the serialized value.
	Name *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Bytes of a BCS serialized value.
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bcs) Reset() {
	*x = Bcs{}
	mi := &file_sui_rpc_v2_bcs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bcs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bcs) ProtoMessage() {}

func (x *Bcs) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_bcs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bcs.ProtoReflect.Descriptor instead.
func (*Bcs) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_bcs_proto_rawDescGZIP(), []int{0}
}

func (x *Bcs) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Bcs) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_sui_rpc_v2_bcs_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_bcs_proto_rawDesc = "" +
	"\n" +
	"\x14sui/rpc/v2/bcs.proto\x12\n" +
	"sui.rpc.v2\"L\n" +
	"\x03Bcs\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x02 \x01(\fH\x01R\x05value\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_valueb\x06proto3"

var (
	file_sui_rpc_v2_bcs_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_bcs_proto_rawDescData []byte
)

func file_sui_rpc_v2_bcs_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_bcs_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_bcs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_bcs_proto_rawDesc), len(file_sui_rpc_v2_bcs_proto_rawDesc)))
	})
	return file_sui_rpc_v2_bcs_proto_rawDescData
}

var file_sui_rpc_v2_bcs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2_bcs_proto_goTypes = []any{
	(*Bcs)(nil), // 0: sui.rpc.v2.Bcs
}
var file_sui_rpc_v2_bcs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_bcs_proto_init() }
func file_sui_rpc_v2_bcs_proto_init() {
	if File_sui_rpc_v2_bcs_proto != nil {
		return
	}
	file_sui_rpc_v2_bcs_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_bcs_proto_rawDesc), len(file_sui_rpc_v2_bcs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_bcs_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_bcs_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_bcs_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_bcs_proto = out.File
	file_sui_rpc_v2_bcs_proto_goTypes = nil
	file_sui_rpc_v2_bcs_proto_depIdxs = nil
}
