// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/event.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Events emitted during the successful execution of a transaction.
type TransactionEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This TransactionEvents serialized as BCS.
	Bcs *Bcs `protobuf:"bytes,1,opt,name=bcs,proto3,oneof" json:"bcs,omitempty"`
	// The digest of this TransactionEvents.
	Digest *string `protobuf:"bytes,2,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// Set of events emitted by a transaction.
	Events        []*Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionEvents) Reset() {
	*x = TransactionEvents{}
	mi := &file_sui_rpc_v2_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvents) ProtoMessage() {}

func (x *TransactionEvents) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvents.ProtoReflect.Descriptor instead.
func (*TransactionEvents) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_event_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionEvents) GetBcs() *Bcs {
	if x != nil {
		return x.Bcs
	}
	return nil
}

func (x *TransactionEvents) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *TransactionEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

// An event.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Package ID of the top-level function invoked by a `MoveCall` command that triggered this
	// event to be emitted.
	PackageId *string `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3,oneof" json:"package_id,omitempty"`
	// Module name of the top-level function invoked by a `MoveCall` command that triggered this
	// event to be emitted.
	Module *string `protobuf:"bytes,2,opt,name=module,proto3,oneof" json:"module,omitempty"`
	// Address of the account that sent the transaction where this event was emitted.
	Sender *string `protobuf:"bytes,3,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	// The type of the event emitted.
	EventType *string `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3,oneof" json:"event_type,omitempty"`
	// BCS serialized bytes of the event.
	Contents *Bcs `protobuf:"bytes,5,opt,name=contents,proto3,oneof" json:"contents,omitempty"`
	// JSON rendering of the event.
	Json          *structpb.Value `protobuf:"bytes,6,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_sui_rpc_v2_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_event_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetPackageId() string {
	if x != nil && x.PackageId != nil {
		return *x.PackageId
	}
	return ""
}

func (x *Event) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

func (x *Event) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

func (x *Event) GetContents() *Bcs {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *Event) GetJson() *structpb.Value {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_sui_rpc_v2_event_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_event_proto_rawDesc = "" +
	"\n" +
	"\x16sui/rpc/v2/event.proto\x12\n" +
	"sui.rpc.v2\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14sui/rpc/v2/bcs.proto\"\x96\x01\n" +
	"\x11TransactionEvents\x12&\n" +
	"\x03bcs\x18\x01 \x01(\v2\x0f.sui.rpc.v2.BcsH\x00R\x03bcs\x88\x01\x01\x12\x1b\n" +
	"\x06digest\x18\x02 \x01(\tH\x01R\x06digest\x88\x01\x01\x12)\n" +
	"\x06events\x18\x03 \x03(\v2\x11.sui.rpc.v2.EventR\x06eventsB\x06\n" +
	"\x04_bcsB\t\n" +
	"\a_digest\"\xb6\x02\n" +
	"\x05Event\x12\"\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tH\x00R\tpackageId\x88\x01\x01\x12\x1b\n" +
	"\x06module\x18\x02 \x01(\tH\x01R\x06module\x88\x01\x01\x12\x1b\n" +
	"\x06sender\x18\x03 \x01(\tH\x02R\x06sender\x88\x01\x01\x12\"\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tH\x03R\teventType\x88\x01\x01\x120\n" +
	"\bcontents\x18\x05 \x01(\v2\x0f.sui.rpc.v2.BcsH\x04R\bcontents\x88\x01\x01\x12/\n" +
	"\x04json\x18\x06 \x01(\v2\x16.google.protobuf.ValueH\x05R\x04json\x88\x01\x01B\r\n" +
	"\v_package_idB\t\n" +
	"\a_moduleB\t\n" +
	"\a_senderB\r\n" +
	"\v_event_typeB\v\n" +
	"\t_contentsB\a\n" +
	"\x05_jsonb\x06proto3"

var (
	file_sui_rpc_v2_event_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_event_proto_rawDescData []byte
)

func file_sui_rpc_v2_event_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_event_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_event_proto_rawDesc), len(file_sui_rpc_v2_event_proto_rawDesc)))
	})
	return file_sui_rpc_v2_event_proto_rawDescData
}

var file_sui_rpc_v2_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sui_rpc_v2_event_proto_goTypes = []any{
	(*TransactionEvents)(nil), // 0: sui.rpc.v2.TransactionEvents
	(*Event)(nil),             // 1: sui.rpc.v2.Event
	(*Bcs)(nil),               // 2: sui.rpc.v2.Bcs
	(*structpb.Value)(nil),    // 3: google.protobuf.Value
}
var file_sui_rpc_v2_event_proto_depIdxs = []int32{
	2, // 0: sui.rpc.v2.TransactionEvents.bcs:type_name -> sui.rpc.v2.Bcs
	1, // 1: sui.rpc.v2.TransactionEvents.events:type_name -> sui.rpc.v2.Event
	2, // 2: sui.rpc.v2.Event.contents:type_name -> sui.rpc.v2.Bcs
	3, // 3: sui.rpc.v2.Event.json:type_name -> google.protobuf.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_event_proto_init() }
func file_sui_rpc_v2_event_proto_init() {
	if File_sui_rpc_v2_event_proto != nil {
		return
	}
	file_sui_rpc_v2_bcs_proto_init()
	file_sui_rpc_v2_event_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2_event_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_event_proto_rawDesc), len(file_sui_rpc_v2_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_event_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_event_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_event_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_event_proto = out.File
	file_sui_rpc_v2_event_proto_goTypes = nil
	file_sui_rpc_v2_event_proto_depIdxs = nil
}
