// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/gas_cost_summary.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Summary of gas charges.
type GasCostSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cost of computation/execution.
	ComputationCost *uint64 `protobuf:"varint,1,opt,name=computation_cost,json=computationCost,proto3,oneof" json:"computation_cost,omitempty"`
	// Storage cost, it's the sum of all storage cost for all objects created or mutated.
	StorageCost *uint64 `protobuf:"varint,2,opt,name=storage_cost,json=storageCost,proto3,oneof" json:"storage_cost,omitempty"`
	// The amount of storage cost refunded to the user for all objects deleted or mutated in the
	// transaction.
	StorageRebate *uint64 `protobuf:"varint,3,opt,name=storage_rebate,json=storageRebate,proto3,oneof" json:"storage_rebate,omitempty"`
	// The fee for the rebate. The portion of the storage rebate kept by the system.
	NonRefundableStorageFee *uint64 `protobuf:"varint,4,opt,name=non_refundable_storage_fee,json=nonRefundableStorageFee,proto3,oneof" json:"non_refundable_storage_fee,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GasCostSummary) Reset() {
	*x = GasCostSummary{}
	mi := &file_sui_rpc_v2_gas_cost_summary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasCostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasCostSummary) ProtoMessage() {}

func (x *GasCostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_gas_cost_summary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasCostSummary.ProtoReflect.Descriptor instead.
func (*GasCostSummary) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_gas_cost_summary_proto_rawDescGZIP(), []int{0}
}

func (x *GasCostSummary) GetComputationCost() uint64 {
	if x != nil && x.ComputationCost != nil {
		return *x.ComputationCost
	}
	return 0
}

func (x *GasCostSummary) GetStorageCost() uint64 {
	if x != nil && x.StorageCost != nil {
		return *x.StorageCost
	}
	return 0
}

func (x *GasCostSummary) GetStorageRebate() uint64 {
	if x != nil && x.StorageRebate != nil {
		return *x.StorageRebate
	}
	return 0
}

func (x *GasCostSummary) GetNonRefundableStorageFee() uint64 {
	if x != nil && x.NonRefundableStorageFee != nil {
		return *x.NonRefundableStorageFee
	}
	return 0
}

var File_sui_rpc_v2_gas_cost_summary_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_gas_cost_summary_proto_rawDesc = "" +
	"\n" +
	"!sui/rpc/v2/gas_cost_summary.proto\x12\n" +
	"sui.rpc.v2\"\xae\x02\n" +
	"\x0eGasCostSummary\x12.\n" +
	"\x10computation_cost\x18\x01 \x01(\x04H\x00R\x0fcomputationCost\x88\x01\x01\x12&\n" +
	"\fstorage_cost\x18\x02 \x01(\x04H\x01R\vstorageCost\x88\x01\x01\x12*\n" +
	"\x0estorage_rebate\x18\x03 \x01(\x04H\x02R\rstorageRebate\x88\x01\x01\x12@\n" +
	"\x1anon_refundable_storage_fee\x18\x04 \x01(\x04H\x03R\x17nonRefundableStorageFee\x88\x01\x01B\x13\n" +
	"\x11_computation_costB\x0f\n" +
	"\r_storage_costB\x11\n" +
	"\x0f_storage_rebateB\x1d\n" +
	"\x1b_non_refundable_storage_feeb\x06proto3"

var (
	file_sui_rpc_v2_gas_cost_summary_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_gas_cost_summary_proto_rawDescData []byte
)

func file_sui_rpc_v2_gas_cost_summary_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_gas_cost_summary_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_gas_cost_summary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_gas_cost_summary_proto_rawDesc), len(file_sui_rpc_v2_gas_cost_summary_proto_rawDesc)))
	})
	return file_sui_rpc_v2_gas_cost_summary_proto_rawDescData
}

var file_sui_rpc_v2_gas_cost_summary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2_gas_cost_summary_proto_goTypes = []any{
	(*GasCostSummary)(nil), // 0: sui.rpc.v2.GasCostSummary
}
var file_sui_rpc_v2_gas_cost_summary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_gas_cost_summary_proto_init() }
func file_sui_rpc_v2_gas_cost_summary_proto_init() {
	if File_sui_rpc_v2_gas_cost_summary_proto != nil {
		return
	}
	file_sui_rpc_v2_gas_cost_summary_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_gas_cost_summary_proto_rawDesc), len(file_sui_rpc_v2_gas_cost_summary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_gas_cost_summary_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_gas_cost_summary_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_gas_cost_summary_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_gas_cost_summary_proto = out.File
	file_sui_rpc_v2_gas_cost_summary_proto_goTypes = nil
	file_sui_rpc_v2_gas_cost_summary_proto_depIdxs = nil
}
