// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/input.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input_InputKind int32

const (
	Input_INPUT_KIND_UNKNOWN Input_InputKind = 0
	// A move value serialized as BCS.
	Input_PURE Input_InputKind = 1
	// A Move object that is either immutable or address owned.
	Input_IMMUTABLE_OR_OWNED Input_InputKind = 2
	// A Move object whose owner is "Shared".
	Input_SHARED Input_InputKind = 3
	// A Move object that is attempted to be received in this transaction.
	Input_RECEIVING Input_InputKind = 4
)

// Enum value maps for Input_InputKind.
var (
	Input_InputKind_name = map[int32]string{
		0: "INPUT_KIND_UNKNOWN",
		1: "PURE",
		2: "IMMUTABLE_OR_OWNED",
		3: "SHARED",
		4: "RECEIVING",
	}
	Input_InputKind_value = map[string]int32{
		"INPUT_KIND_UNKNOWN": 0,
		"PURE":               1,
		"IMMUTABLE_OR_OWNED": 2,
		"SHARED":             3,
		"RECEIVING":          4,
	}
)

func (x Input_InputKind) Enum() *Input_InputKind {
	p := new(Input_InputKind)
	*p = x
	return p
}

func (x Input_InputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Input_InputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2_input_proto_enumTypes[0].Descriptor()
}

func (Input_InputKind) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2_input_proto_enumTypes[0]
}

func (x Input_InputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Input_InputKind.Descriptor instead.
func (Input_InputKind) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2_input_proto_rawDescGZIP(), []int{0, 0}
}

// An input to a user transaction.
type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  *Input_InputKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=sui.rpc.v2.Input_InputKind,oneof" json:"kind,omitempty"`
	// A move value serialized as BCS.
	//
	// For normal operations this is required to be a move primitive type and not contain structs
	// or objects.
	Pure []byte `protobuf:"bytes,2,opt,name=pure,proto3,oneof" json:"pure,omitempty"`
	// `ObjectId` of the object input.
	ObjectId *string `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	// Requested version of the input object when `kind` is `IMMUTABLE_OR_OWNED`
	// or `RECEIVING` or if `kind` is `SHARED` this is the initial version of the
	// object when it was shared
	Version *uint64 `protobuf:"varint,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// The digest of this object.
	Digest *string `protobuf:"bytes,5,opt,name=digest,proto3,oneof" json:"digest,omitempty"`
	// Controls whether the caller asks for a mutable reference to the shared
	// object.
	Mutable *bool `protobuf:"varint,6,opt,name=mutable,proto3,oneof" json:"mutable,omitempty"`
	// A literal value
	//
	// INPUT ONLY
	Literal       *structpb.Value `protobuf:"bytes,1000,opt,name=literal,proto3,oneof" json:"literal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_sui_rpc_v2_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_input_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetKind() Input_InputKind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Input_INPUT_KIND_UNKNOWN
}

func (x *Input) GetPure() []byte {
	if x != nil {
		return x.Pure
	}
	return nil
}

func (x *Input) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

func (x *Input) GetVersion() uint64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *Input) GetDigest() string {
	if x != nil && x.Digest != nil {
		return *x.Digest
	}
	return ""
}

func (x *Input) GetMutable() bool {
	if x != nil && x.Mutable != nil {
		return *x.Mutable
	}
	return false
}

func (x *Input) GetLiteral() *structpb.Value {
	if x != nil {
		return x.Literal
	}
	return nil
}

var File_sui_rpc_v2_input_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_input_proto_rawDesc = "" +
	"\n" +
	"\x16sui/rpc/v2/input.proto\x12\n" +
	"sui.rpc.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xbc\x03\n" +
	"\x05Input\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.sui.rpc.v2.Input.InputKindH\x00R\x04kind\x88\x01\x01\x12\x17\n" +
	"\x04pure\x18\x02 \x01(\fH\x01R\x04pure\x88\x01\x01\x12 \n" +
	"\tobject_id\x18\x03 \x01(\tH\x02R\bobjectId\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\x04H\x03R\aversion\x88\x01\x01\x12\x1b\n" +
	"\x06digest\x18\x05 \x01(\tH\x04R\x06digest\x88\x01\x01\x12\x1d\n" +
	"\amutable\x18\x06 \x01(\bH\x05R\amutable\x88\x01\x01\x126\n" +
	"\aliteral\x18\xe8\a \x01(\v2\x16.google.protobuf.ValueH\x06R\aliteral\x88\x01\x01\"`\n" +
	"\tInputKind\x12\x16\n" +
	"\x12INPUT_KIND_UNKNOWN\x10\x00\x12\b\n" +
	"\x04PURE\x10\x01\x12\x16\n" +
	"\x12IMMUTABLE_OR_OWNED\x10\x02\x12\n" +
	"\n" +
	"\x06SHARED\x10\x03\x12\r\n" +
	"\tRECEIVING\x10\x04B\a\n" +
	"\x05_kindB\a\n" +
	"\x05_pureB\f\n" +
	"\n" +
	"_object_idB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_digestB\n" +
	"\n" +
	"\b_mutableB\n" +
	"\n" +
	"\b_literalb\x06proto3"

var (
	file_sui_rpc_v2_input_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_input_proto_rawDescData []byte
)

func file_sui_rpc_v2_input_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_input_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_input_proto_rawDesc), len(file_sui_rpc_v2_input_proto_rawDesc)))
	})
	return file_sui_rpc_v2_input_proto_rawDescData
}

var file_sui_rpc_v2_input_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sui_rpc_v2_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2_input_proto_goTypes = []any{
	(Input_InputKind)(0),   // 0: sui.rpc.v2.Input.InputKind
	(*Input)(nil),          // 1: sui.rpc.v2.Input
	(*structpb.Value)(nil), // 2: google.protobuf.Value
}
var file_sui_rpc_v2_input_proto_depIdxs = []int32{
	0, // 0: sui.rpc.v2.Input.kind:type_name -> sui.rpc.v2.Input.InputKind
	2, // 1: sui.rpc.v2.Input.literal:type_name -> google.protobuf.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_input_proto_init() }
func file_sui_rpc_v2_input_proto_init() {
	if File_sui_rpc_v2_input_proto != nil {
		return
	}
	file_sui_rpc_v2_input_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_input_proto_rawDesc), len(file_sui_rpc_v2_input_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_input_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_input_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2_input_proto_enumTypes,
		MessageInfos:      file_sui_rpc_v2_input_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_input_proto = out.File
	file_sui_rpc_v2_input_proto_goTypes = nil
	file_sui_rpc_v2_input_proto_depIdxs = nil
}
