// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/name_service.proto

package v2

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The SuiNS name to lookup.
	//
	// Supports both `@name` as well as `name.sui` formats.
	Name          *string `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupNameRequest) Reset() {
	*x = LookupNameRequest{}
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameRequest) ProtoMessage() {}

func (x *LookupNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameRequest.ProtoReflect.Descriptor instead.
func (*LookupNameRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_name_service_proto_rawDescGZIP(), []int{0}
}

func (x *LookupNameRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type LookupNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record for the requested name
	Record        *NameRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupNameResponse) Reset() {
	*x = LookupNameResponse{}
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameResponse) ProtoMessage() {}

func (x *LookupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameResponse.ProtoReflect.Descriptor instead.
func (*LookupNameResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_name_service_proto_rawDescGZIP(), []int{1}
}

func (x *LookupNameResponse) GetRecord() *NameRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ReverseLookupNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The address to perform a reverse lookup for.
	Address       *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseLookupNameRequest) Reset() {
	*x = ReverseLookupNameRequest{}
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseLookupNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseLookupNameRequest) ProtoMessage() {}

func (x *ReverseLookupNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseLookupNameRequest.ProtoReflect.Descriptor instead.
func (*ReverseLookupNameRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_name_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReverseLookupNameRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

type ReverseLookupNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The record for the SuiNS name linked to the requested address
	Record        *NameRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseLookupNameResponse) Reset() {
	*x = ReverseLookupNameResponse{}
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseLookupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseLookupNameResponse) ProtoMessage() {}

func (x *ReverseLookupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseLookupNameResponse.ProtoReflect.Descriptor instead.
func (*ReverseLookupNameResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_name_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseLookupNameResponse) GetRecord() *NameRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type NameRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of this record.
	//
	// Note that records are stored on chain as dynamic fields of the type
	// `Field<Domain,NameRecord>`.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The SuiNS name of this record
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The ID of the `RegistrationNFT` assigned to this record.
	//
	// The owner of the corresponding `RegistrationNFT` has the rights to
	// be able to change and adjust the `target_address` of this domain.
	//
	// It is possible that the ID changes if the record expires and is
	// purchased by someone else.
	RegistrationNftId *string `protobuf:"bytes,3,opt,name=registration_nft_id,json=registrationNftId,proto3,oneof" json:"registration_nft_id,omitempty"`
	// Timestamp when the record expires.
	//
	// This is either the expiration of the record itself or the expiration of
	// this record's parent if this is a leaf record.
	ExpirationTimestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=expiration_timestamp,json=expirationTimestamp,proto3,oneof" json:"expiration_timestamp,omitempty"`
	// The target address that this name points to
	TargetAddress *string `protobuf:"bytes,5,opt,name=target_address,json=targetAddress,proto3,oneof" json:"target_address,omitempty"`
	// Additional data which may be stored in a record
	Data          map[string]string `protobuf:"bytes,6,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameRecord) Reset() {
	*x = NameRecord{}
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameRecord) ProtoMessage() {}

func (x *NameRecord) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_name_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameRecord.ProtoReflect.Descriptor instead.
func (*NameRecord) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_name_service_proto_rawDescGZIP(), []int{4}
}

func (x *NameRecord) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *NameRecord) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameRecord) GetRegistrationNftId() string {
	if x != nil && x.RegistrationNftId != nil {
		return *x.RegistrationNftId
	}
	return ""
}

func (x *NameRecord) GetExpirationTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.ExpirationTimestamp
	}
	return nil
}

func (x *NameRecord) GetTargetAddress() string {
	if x != nil && x.TargetAddress != nil {
		return *x.TargetAddress
	}
	return ""
}

func (x *NameRecord) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_sui_rpc_v2_name_service_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_name_service_proto_rawDesc = "" +
	"\n" +
	"\x1dsui/rpc/v2/name_service.proto\x12\n" +
	"sui.rpc.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\x11LookupNameRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"T\n" +
	"\x12LookupNameResponse\x123\n" +
	"\x06record\x18\x01 \x01(\v2\x16.sui.rpc.v2.NameRecordH\x00R\x06record\x88\x01\x01B\t\n" +
	"\a_record\"E\n" +
	"\x18ReverseLookupNameRequest\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address\"[\n" +
	"\x19ReverseLookupNameResponse\x123\n" +
	"\x06record\x18\x01 \x01(\v2\x16.sui.rpc.v2.NameRecordH\x00R\x06record\x88\x01\x01B\t\n" +
	"\a_record\"\xb2\x03\n" +
	"\n" +
	"NameRecord\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x123\n" +
	"\x13registration_nft_id\x18\x03 \x01(\tH\x02R\x11registrationNftId\x88\x01\x01\x12R\n" +
	"\x14expiration_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x13expirationTimestamp\x88\x01\x01\x12*\n" +
	"\x0etarget_address\x18\x05 \x01(\tH\x04R\rtargetAddress\x88\x01\x01\x124\n" +
	"\x04data\x18\x06 \x03(\v2 .sui.rpc.v2.NameRecord.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\x16\n" +
	"\x14_registration_nft_idB\x17\n" +
	"\x15_expiration_timestampB\x11\n" +
	"\x0f_target_address2\xbc\x01\n" +
	"\vNameService\x12K\n" +
	"\n" +
	"LookupName\x12\x1d.sui.rpc.v2.LookupNameRequest\x1a\x1e.sui.rpc.v2.LookupNameResponse\x12`\n" +
	"\x11ReverseLookupName\x12$.sui.rpc.v2.ReverseLookupNameRequest\x1a%.sui.rpc.v2.ReverseLookupNameResponseb\x06proto3"

var (
	file_sui_rpc_v2_name_service_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_name_service_proto_rawDescData []byte
)

func file_sui_rpc_v2_name_service_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_name_service_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_name_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_name_service_proto_rawDesc), len(file_sui_rpc_v2_name_service_proto_rawDesc)))
	})
	return file_sui_rpc_v2_name_service_proto_rawDescData
}

var file_sui_rpc_v2_name_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sui_rpc_v2_name_service_proto_goTypes = []any{
	(*LookupNameRequest)(nil),         // 0: sui.rpc.v2.LookupNameRequest
	(*LookupNameResponse)(nil),        // 1: sui.rpc.v2.LookupNameResponse
	(*ReverseLookupNameRequest)(nil),  // 2: sui.rpc.v2.ReverseLookupNameRequest
	(*ReverseLookupNameResponse)(nil), // 3: sui.rpc.v2.ReverseLookupNameResponse
	(*NameRecord)(nil),                // 4: sui.rpc.v2.NameRecord
	nil,                               // 5: sui.rpc.v2.NameRecord.DataEntry
	(*timestamp.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_sui_rpc_v2_name_service_proto_depIdxs = []int32{
	4, // 0: sui.rpc.v2.LookupNameResponse.record:type_name -> sui.rpc.v2.NameRecord
	4, // 1: sui.rpc.v2.ReverseLookupNameResponse.record:type_name -> sui.rpc.v2.NameRecord
	6, // 2: sui.rpc.v2.NameRecord.expiration_timestamp:type_name -> google.protobuf.Timestamp
	5, // 3: sui.rpc.v2.NameRecord.data:type_name -> sui.rpc.v2.NameRecord.DataEntry
	0, // 4: sui.rpc.v2.NameService.LookupName:input_type -> sui.rpc.v2.LookupNameRequest
	2, // 5: sui.rpc.v2.NameService.ReverseLookupName:input_type -> sui.rpc.v2.ReverseLookupNameRequest
	1, // 6: sui.rpc.v2.NameService.LookupName:output_type -> sui.rpc.v2.LookupNameResponse
	3, // 7: sui.rpc.v2.NameService.ReverseLookupName:output_type -> sui.rpc.v2.ReverseLookupNameResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_name_service_proto_init() }
func file_sui_rpc_v2_name_service_proto_init() {
	if File_sui_rpc_v2_name_service_proto != nil {
		return
	}
	file_sui_rpc_v2_name_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2_name_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2_name_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_sui_rpc_v2_name_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_sui_rpc_v2_name_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_name_service_proto_rawDesc), len(file_sui_rpc_v2_name_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sui_rpc_v2_name_service_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_name_service_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_name_service_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_name_service_proto = out.File
	file_sui_rpc_v2_name_service_proto_goTypes = nil
	file_sui_rpc_v2_name_service_proto_depIdxs = nil
}
