// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: sui/rpc/v2/signature_verification_service.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignatureVerificationService_VerifySignature_FullMethodName = "/sui.rpc.v2.SignatureVerificationService/VerifySignature"
)

// SignatureVerificationServiceClient is the client API for SignatureVerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignatureVerificationServiceClient interface {
	// Perform signature verification of a UserSignature against the provided message.
	VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
}

type signatureVerificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignatureVerificationServiceClient(cc grpc.ClientConnInterface) SignatureVerificationServiceClient {
	return &signatureVerificationServiceClient{cc}
}

func (c *signatureVerificationServiceClient) VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, SignatureVerificationService_VerifySignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignatureVerificationServiceServer is the server API for SignatureVerificationService service.
// All implementations must embed UnimplementedSignatureVerificationServiceServer
// for forward compatibility.
type SignatureVerificationServiceServer interface {
	// Perform signature verification of a UserSignature against the provided message.
	VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	mustEmbedUnimplementedSignatureVerificationServiceServer()
}

// UnimplementedSignatureVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignatureVerificationServiceServer struct{}

func (UnimplementedSignatureVerificationServiceServer) VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignature not implemented")
}
func (UnimplementedSignatureVerificationServiceServer) mustEmbedUnimplementedSignatureVerificationServiceServer() {
}
func (UnimplementedSignatureVerificationServiceServer) testEmbeddedByValue() {}

// UnsafeSignatureVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignatureVerificationServiceServer will
// result in compilation errors.
type UnsafeSignatureVerificationServiceServer interface {
	mustEmbedUnimplementedSignatureVerificationServiceServer()
}

func RegisterSignatureVerificationServiceServer(s grpc.ServiceRegistrar, srv SignatureVerificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignatureVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignatureVerificationService_ServiceDesc, srv)
}

func _SignatureVerificationService_VerifySignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureVerificationServiceServer).VerifySignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignatureVerificationService_VerifySignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureVerificationServiceServer).VerifySignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignatureVerificationService_ServiceDesc is the grpc.ServiceDesc for SignatureVerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignatureVerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.SignatureVerificationService",
	HandlerType: (*SignatureVerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifySignature",
			Handler:    _SignatureVerificationService_VerifySignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sui/rpc/v2/signature_verification_service.proto",
}
