// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: sui/rpc/v2/transaction_execution_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
type SimulateTransactionRequest_TransactionChecks int32

const (
	SimulateTransactionRequest_ENABLED  SimulateTransactionRequest_TransactionChecks = 0
	SimulateTransactionRequest_DISABLED SimulateTransactionRequest_TransactionChecks = 1
)

// Enum value maps for SimulateTransactionRequest_TransactionChecks.
var (
	SimulateTransactionRequest_TransactionChecks_name = map[int32]string{
		0: "ENABLED",
		1: "DISABLED",
	}
	SimulateTransactionRequest_TransactionChecks_value = map[string]int32{
		"ENABLED":  0,
		"DISABLED": 1,
	}
)

func (x SimulateTransactionRequest_TransactionChecks) Enum() *SimulateTransactionRequest_TransactionChecks {
	p := new(SimulateTransactionRequest_TransactionChecks)
	*p = x
	return p
}

func (x SimulateTransactionRequest_TransactionChecks) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulateTransactionRequest_TransactionChecks) Descriptor() protoreflect.EnumDescriptor {
	return file_sui_rpc_v2_transaction_execution_service_proto_enumTypes[0].Descriptor()
}

func (SimulateTransactionRequest_TransactionChecks) Type() protoreflect.EnumType {
	return &file_sui_rpc_v2_transaction_execution_service_proto_enumTypes[0]
}

func (x SimulateTransactionRequest_TransactionChecks) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulateTransactionRequest_TransactionChecks.Descriptor instead.
func (SimulateTransactionRequest_TransactionChecks) EnumDescriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{2, 0}
}

type ExecuteTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The transaction to execute.
	Transaction *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// Set of `UserSignature`s authorizing the execution of the provided
	// transaction.
	Signatures []*UserSignature `protobuf:"bytes,2,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Mask specifying which fields to read.
	// If no mask is specified, defaults to `effects.status,checkpoint`.
	ReadMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionRequest) Reset() {
	*x = ExecuteTransactionRequest{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionRequest) ProtoMessage() {}

func (x *ExecuteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ExecuteTransactionRequest) GetSignatures() []*UserSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *ExecuteTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

// Response message for `NodeService.ExecuteTransaction`.
type ExecuteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *ExecutedTransaction   `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTransactionResponse) Reset() {
	*x = ExecuteTransactionResponse{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTransactionResponse) ProtoMessage() {}

func (x *ExecuteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTransactionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTransactionResponse) GetTransaction() *ExecutedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SimulateTransactionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	// Mask specifying which fields to read.
	ReadMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=read_mask,json=readMask,proto3,oneof" json:"read_mask,omitempty"`
	// Specify whether checks should be ENABLED (default) or DISABLED while executing the transaction
	Checks *SimulateTransactionRequest_TransactionChecks `protobuf:"varint,3,opt,name=checks,proto3,enum=sui.rpc.v2.SimulateTransactionRequest_TransactionChecks,oneof" json:"checks,omitempty"`
	// Perform gas selection based on a budget estimation and include the
	// selected gas payment and budget in the response.
	//
	// This option will be ignored if `checks` is `DISABLED`.
	DoGasSelection *bool `protobuf:"varint,4,opt,name=do_gas_selection,json=doGasSelection,proto3,oneof" json:"do_gas_selection,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulateTransactionRequest) Reset() {
	*x = SimulateTransactionRequest{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionRequest) ProtoMessage() {}

func (x *SimulateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionRequest.ProtoReflect.Descriptor instead.
func (*SimulateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{2}
}

func (x *SimulateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionRequest) GetReadMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.ReadMask
	}
	return nil
}

func (x *SimulateTransactionRequest) GetChecks() SimulateTransactionRequest_TransactionChecks {
	if x != nil && x.Checks != nil {
		return *x.Checks
	}
	return SimulateTransactionRequest_ENABLED
}

func (x *SimulateTransactionRequest) GetDoGasSelection() bool {
	if x != nil && x.DoGasSelection != nil {
		return *x.DoGasSelection
	}
	return false
}

type SimulateTransactionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Transaction    *ExecutedTransaction   `protobuf:"bytes,1,opt,name=transaction,proto3,oneof" json:"transaction,omitempty"`
	CommandOutputs []*CommandResult       `protobuf:"bytes,2,rep,name=command_outputs,json=commandOutputs,proto3" json:"command_outputs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulateTransactionResponse) Reset() {
	*x = SimulateTransactionResponse{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionResponse) ProtoMessage() {}

func (x *SimulateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionResponse.ProtoReflect.Descriptor instead.
func (*SimulateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{3}
}

func (x *SimulateTransactionResponse) GetTransaction() *ExecutedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionResponse) GetCommandOutputs() []*CommandResult {
	if x != nil {
		return x.CommandOutputs
	}
	return nil
}

// An intermediate result/output from the execution of a single command
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReturnValues  []*CommandOutput       `protobuf:"bytes,1,rep,name=return_values,json=returnValues,proto3" json:"return_values,omitempty"`
	MutatedByRef  []*CommandOutput       `protobuf:"bytes,2,rep,name=mutated_by_ref,json=mutatedByRef,proto3" json:"mutated_by_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResult) GetReturnValues() []*CommandOutput {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

func (x *CommandResult) GetMutatedByRef() []*CommandOutput {
	if x != nil {
		return x.MutatedByRef
	}
	return nil
}

type CommandOutput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Argument *Argument              `protobuf:"bytes,1,opt,name=argument,proto3,oneof" json:"argument,omitempty"`
	Value    *Bcs                   `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// JSON rendering of the output.
	Json          *structpb.Value `protobuf:"bytes,3,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandOutput) Reset() {
	*x = CommandOutput{}
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandOutput) ProtoMessage() {}

func (x *CommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandOutput.ProtoReflect.Descriptor instead.
func (*CommandOutput) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP(), []int{5}
}

func (x *CommandOutput) GetArgument() *Argument {
	if x != nil {
		return x.Argument
	}
	return nil
}

func (x *CommandOutput) GetValue() *Bcs {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CommandOutput) GetJson() *structpb.Value {
	if x != nil {
		return x.Json
	}
	return nil
}

var File_sui_rpc_v2_transaction_execution_service_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_transaction_execution_service_proto_rawDesc = "" +
	"\n" +
	".sui/rpc/v2/transaction_execution_service.proto\x12\n" +
	"sui.rpc.v2\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19sui/rpc/v2/argument.proto\x1a\x14sui/rpc/v2/bcs.proto\x1a%sui/rpc/v2/executed_transaction.proto\x1a\x1asui/rpc/v2/signature.proto\x1a\x1csui/rpc/v2/transaction.proto\"\xf2\x01\n" +
	"\x19ExecuteTransactionRequest\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x17.sui.rpc.v2.TransactionH\x00R\vtransaction\x88\x01\x01\x129\n" +
	"\n" +
	"signatures\x18\x02 \x03(\v2\x19.sui.rpc.v2.UserSignatureR\n" +
	"signatures\x12<\n" +
	"\tread_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01B\x0e\n" +
	"\f_transactionB\f\n" +
	"\n" +
	"_read_mask\"t\n" +
	"\x1aExecuteTransactionResponse\x12F\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1f.sui.rpc.v2.ExecutedTransactionH\x00R\vtransaction\x88\x01\x01B\x0e\n" +
	"\f_transaction\"\x8e\x03\n" +
	"\x1aSimulateTransactionRequest\x12>\n" +
	"\vtransaction\x18\x01 \x01(\v2\x17.sui.rpc.v2.TransactionH\x00R\vtransaction\x88\x01\x01\x12<\n" +
	"\tread_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x01R\breadMask\x88\x01\x01\x12U\n" +
	"\x06checks\x18\x03 \x01(\x0e28.sui.rpc.v2.SimulateTransactionRequest.TransactionChecksH\x02R\x06checks\x88\x01\x01\x12-\n" +
	"\x10do_gas_selection\x18\x04 \x01(\bH\x03R\x0edoGasSelection\x88\x01\x01\".\n" +
	"\x11TransactionChecks\x12\v\n" +
	"\aENABLED\x10\x00\x12\f\n" +
	"\bDISABLED\x10\x01B\x0e\n" +
	"\f_transactionB\f\n" +
	"\n" +
	"_read_maskB\t\n" +
	"\a_checksB\x13\n" +
	"\x11_do_gas_selection\"\xb9\x01\n" +
	"\x1bSimulateTransactionResponse\x12F\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1f.sui.rpc.v2.ExecutedTransactionH\x00R\vtransaction\x88\x01\x01\x12B\n" +
	"\x0fcommand_outputs\x18\x02 \x03(\v2\x19.sui.rpc.v2.CommandResultR\x0ecommandOutputsB\x0e\n" +
	"\f_transaction\"\x90\x01\n" +
	"\rCommandResult\x12>\n" +
	"\rreturn_values\x18\x01 \x03(\v2\x19.sui.rpc.v2.CommandOutputR\freturnValues\x12?\n" +
	"\x0emutated_by_ref\x18\x02 \x03(\v2\x19.sui.rpc.v2.CommandOutputR\fmutatedByRef\"\xc3\x01\n" +
	"\rCommandOutput\x125\n" +
	"\bargument\x18\x01 \x01(\v2\x14.sui.rpc.v2.ArgumentH\x00R\bargument\x88\x01\x01\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.sui.rpc.v2.BcsH\x01R\x05value\x88\x01\x01\x12/\n" +
	"\x04json\x18\x03 \x01(\v2\x16.google.protobuf.ValueH\x02R\x04json\x88\x01\x01B\v\n" +
	"\t_argumentB\b\n" +
	"\x06_valueB\a\n" +
	"\x05_json2\xea\x01\n" +
	"\x1bTransactionExecutionService\x12c\n" +
	"\x12ExecuteTransaction\x12%.sui.rpc.v2.ExecuteTransactionRequest\x1a&.sui.rpc.v2.ExecuteTransactionResponse\x12f\n" +
	"\x13SimulateTransaction\x12&.sui.rpc.v2.SimulateTransactionRequest\x1a'.sui.rpc.v2.SimulateTransactionResponseb\x06proto3"

var (
	file_sui_rpc_v2_transaction_execution_service_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_transaction_execution_service_proto_rawDescData []byte
)

func file_sui_rpc_v2_transaction_execution_service_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_transaction_execution_service_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_transaction_execution_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_transaction_execution_service_proto_rawDesc), len(file_sui_rpc_v2_transaction_execution_service_proto_rawDesc)))
	})
	return file_sui_rpc_v2_transaction_execution_service_proto_rawDescData
}

var file_sui_rpc_v2_transaction_execution_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sui_rpc_v2_transaction_execution_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sui_rpc_v2_transaction_execution_service_proto_goTypes = []any{
	(SimulateTransactionRequest_TransactionChecks)(0), // 0: sui.rpc.v2.SimulateTransactionRequest.TransactionChecks
	(*ExecuteTransactionRequest)(nil),                 // 1: sui.rpc.v2.ExecuteTransactionRequest
	(*ExecuteTransactionResponse)(nil),                // 2: sui.rpc.v2.ExecuteTransactionResponse
	(*SimulateTransactionRequest)(nil),                // 3: sui.rpc.v2.SimulateTransactionRequest
	(*SimulateTransactionResponse)(nil),               // 4: sui.rpc.v2.SimulateTransactionResponse
	(*CommandResult)(nil),                             // 5: sui.rpc.v2.CommandResult
	(*CommandOutput)(nil),                             // 6: sui.rpc.v2.CommandOutput
	(*Transaction)(nil),                               // 7: sui.rpc.v2.Transaction
	(*UserSignature)(nil),                             // 8: sui.rpc.v2.UserSignature
	(*fieldmaskpb.FieldMask)(nil),                     // 9: google.protobuf.FieldMask
	(*ExecutedTransaction)(nil),                       // 10: sui.rpc.v2.ExecutedTransaction
	(*Argument)(nil),                                  // 11: sui.rpc.v2.Argument
	(*Bcs)(nil),                                       // 12: sui.rpc.v2.Bcs
	(*structpb.Value)(nil),                            // 13: google.protobuf.Value
}
var file_sui_rpc_v2_transaction_execution_service_proto_depIdxs = []int32{
	7,  // 0: sui.rpc.v2.ExecuteTransactionRequest.transaction:type_name -> sui.rpc.v2.Transaction
	8,  // 1: sui.rpc.v2.ExecuteTransactionRequest.signatures:type_name -> sui.rpc.v2.UserSignature
	9,  // 2: sui.rpc.v2.ExecuteTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	10, // 3: sui.rpc.v2.ExecuteTransactionResponse.transaction:type_name -> sui.rpc.v2.ExecutedTransaction
	7,  // 4: sui.rpc.v2.SimulateTransactionRequest.transaction:type_name -> sui.rpc.v2.Transaction
	9,  // 5: sui.rpc.v2.SimulateTransactionRequest.read_mask:type_name -> google.protobuf.FieldMask
	0,  // 6: sui.rpc.v2.SimulateTransactionRequest.checks:type_name -> sui.rpc.v2.SimulateTransactionRequest.TransactionChecks
	10, // 7: sui.rpc.v2.SimulateTransactionResponse.transaction:type_name -> sui.rpc.v2.ExecutedTransaction
	5,  // 8: sui.rpc.v2.SimulateTransactionResponse.command_outputs:type_name -> sui.rpc.v2.CommandResult
	6,  // 9: sui.rpc.v2.CommandResult.return_values:type_name -> sui.rpc.v2.CommandOutput
	6,  // 10: sui.rpc.v2.CommandResult.mutated_by_ref:type_name -> sui.rpc.v2.CommandOutput
	11, // 11: sui.rpc.v2.CommandOutput.argument:type_name -> sui.rpc.v2.Argument
	12, // 12: sui.rpc.v2.CommandOutput.value:type_name -> sui.rpc.v2.Bcs
	13, // 13: sui.rpc.v2.CommandOutput.json:type_name -> google.protobuf.Value
	1,  // 14: sui.rpc.v2.TransactionExecutionService.ExecuteTransaction:input_type -> sui.rpc.v2.ExecuteTransactionRequest
	3,  // 15: sui.rpc.v2.TransactionExecutionService.SimulateTransaction:input_type -> sui.rpc.v2.SimulateTransactionRequest
	2,  // 16: sui.rpc.v2.TransactionExecutionService.ExecuteTransaction:output_type -> sui.rpc.v2.ExecuteTransactionResponse
	4,  // 17: sui.rpc.v2.TransactionExecutionService.SimulateTransaction:output_type -> sui.rpc.v2.SimulateTransactionResponse
	16, // [16:18] is the sub-list for method output_type
	14, // [14:16] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_transaction_execution_service_proto_init() }
func file_sui_rpc_v2_transaction_execution_service_proto_init() {
	if File_sui_rpc_v2_transaction_execution_service_proto != nil {
		return
	}
	file_sui_rpc_v2_argument_proto_init()
	file_sui_rpc_v2_bcs_proto_init()
	file_sui_rpc_v2_executed_transaction_proto_init()
	file_sui_rpc_v2_signature_proto_init()
	file_sui_rpc_v2_transaction_proto_init()
	file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_sui_rpc_v2_transaction_execution_service_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_transaction_execution_service_proto_rawDesc), len(file_sui_rpc_v2_transaction_execution_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sui_rpc_v2_transaction_execution_service_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_transaction_execution_service_proto_depIdxs,
		EnumInfos:         file_sui_rpc_v2_transaction_execution_service_proto_enumTypes,
		MessageInfos:      file_sui_rpc_v2_transaction_execution_service_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_transaction_execution_service_proto = out.File
	file_sui_rpc_v2_transaction_execution_service_proto_goTypes = nil
	file_sui_rpc_v2_transaction_execution_service_proto_depIdxs = nil
}
